### ISSUE TITLE
how to set the log mode to topic 

### ISSUE THREAD

**Issue by caferain0** [emqx/emqx#103]
how to set the log mode to topic, insteads of  stdout. thanks

**Comment by erylee** [comment]
not support this feature now.

could you write the requirements in detail?

**Comment by caferain0** [comment]
there is  the requirements  to  get the every client's status of connected and disconnected.

1. with Mosquitto 
the parameter log_dest (send log messages to a particular destination. Possible destinations are: stdout stderr syslog topic).
Set the log_dest to topic, then in my own code, subscribe to the topics like this:
  new Topic("$SYS/broker/log/E",QoS.AT_LEAST_ONCE),
  new Topic("$SYS/broker/log/W",QoS.AT_LEAST_ONCE),
  new Topic("$SYS/broker/log/N",QoS.AT_LEAST_ONCE),
  new Topic("$SYS/broker/log/I",QoS.AT_LEAST_ONCE),
Then analyze the messages of the topic to get the every client's status.(connected, disconnecting,timeout, Socket read error....)  with token id.

2. with emqttd
the log destination is just stdout.  how to deal with the requirements mentioned above, thanks!

**Comment by erylee** [comment]
hi, this feature will be released in 0.7.x after websocket support.

**Comment by erylee** [comment]
@caferain0, emqttd 0.8.1 release with a new feature: [Presence](https://github.com/emqtt/emqttd/wiki/Presence). 

When client connected or disconnected, broker will publish messages to $SYS topics:

```
$SYS/borkers/${broker}/clients/${clientId}/connected
$SYS/borkers/${broker}/clients/${clientId}/disconnected
```

**Comment by phanimahesh** [comment]
@erylee The connected and disconnected messages being published to $SYS topics will solve the example @caferain0 was referring to, but the more generic use case of sending logs to a topic is not currently possible. A user might want to stream the logs to a log aggregation server for processing on a different machine, for instance.

At minimum, here are the changes that are required:
 - Instead of directly calling `lager`'s methods, have a single function maybe `emqttd:log` to handle all logging.
 - Allow user to specify a topic as target for logs. In this case, any log messages are published to this topic.

Or alternately, always publish logs to a topic, and by default have a client subscribe to this topic and send logs to lager. This might have some performance impact, though, not sure.

**Comment by erylee** [comment]
@phanimahesh, I did not support this feature for performance issue. If all the logs published to one topic, an erlang proccess may be overloaded. 

So I think we should support "shared subscription" feature in issue #191 first and then redesign the log. Thanks for your suggestion:)
