### ISSUE TITLE
Add cache to rate limit

### ISSUE THREAD

**Issue by ivanbearcat** [emqx/emqx#10730]
### What would you like to be added or enhanced?

When I use message_routing in the rate limit, messages will be discarded when the rate exceeds the limit. Can you add a cache to ensure that messages will not be discarded and send messages in the cache after the rate decreases?

### Why is this needed?

We want to use message_routing for rate limiting without losing messages

**Comment by keynslug** [comment]
Hi, @ivanbearcat!

I'd say that would defeat the purpose of rate limiting mechanisms, honestly. However it sounds to me like you're thinking about burst rate control, which should be supported by EMQX. You might play with `capacity` limiter configuration parameter (`burst` [since 5.0.25](https://github.com/emqx/emqx/pull/10376)), see this chapter in documentation.

https://www.emqx.io/docs/en/v5.0/rate-limit/rate-limit.html

**Comment by ivanbearcat** [comment]
When the rate is too high, the consumer may not be able to handle it. Therefore, the consumer hopes to eliminate the peak value by limiting the rate, but does not want to discard the message

**Comment by lafirest** [comment]
@ivanbearcat 
Hi, the behaviour when over the limit is under discussion, but the `message_routing` and all client options were deprecated since v5.0.25, we only kept the `rate` in the configuration to simplify its use. 
Could you give us some advice or idea from your situation, thanks you

**Comment by ivanbearcat** [comment]
Our requirement is that messages will not be lost when the rate is limited. Can we add a cache queue where messages suspended receive and sent can be stored temporarily until the rate drops

**Comment by zmstone** [comment]
closing this issue since the routing limiter is removed.
