### ISSUE TITLE
jq error with version 5.1.1: jq error: Cannot iterate over null (null)

### ISSUE THREAD

**Issue by steffstefferson** [emqx/emqx#11467]
### What happened?

When upgrading from emqx enterprise 5.1.0 to 5.1.1 the following rule started throwing exceptions:

 SELECT
      payload.mailpieceId,
      payload.timestamp as payload.scanned.timestamp,
      payload.sourceId as payload.scanned.sourceId,
      payload.imageKey as payload.scanned.imageKey,
      substr(payload.imageKey, 0, 6) as payload.scanned.postcode6,
      jq('.mpAttr.preknowledge.barCodes[] | (if .type == "DATA_MATRIX" and .status == "DETECTED_AND_RECOGNIZED" and 
      select(.value | startswith("756")) then . else empty end)', payload) as payload.scanned.barcodes  
    FROM
      "bridge/par-atg-kafka/#"
   
In our logs we see the following error:
[warning] msg: SELECT_clause_exception, mfa: emqx_rule_runtime:apply_rule/3, line: 81, reason: {throw,{jq_exception,{jq_err_process,<<"jq error: Cannot iterate over null (null)\n">>}},

<details>

 [warning] msg: SELECT_clause_exception, mfa: emqx_rule_runtime:apply_rule/3, line: 81, reason: {throw,{jq_exception,{jq_err_process,<<"jq error: Cannot iterate over null (null)\n">>}},[{emqx_rule_funcs,jq,3,[{file,"emqx_rule_funcs.erl"},{line,852}]},{emqx_rule_runtime,do_apply_func,4,[{file,"emqx_rule_runtime.erl"},{line,496}]},{emqx_rule_runtime,select_and_transform,3,[{file,"emqx_rule_runtime.erl"},{line,198}]},{emqx_rule_runtime,do_apply_rule,3,[{file,"emqx_rule_runtime.erl"},{line,169}]},{emqx_rule_runtime,apply_rule,3,[{file,"emqx_rule_runtime.erl"},{line,72}]},{emqx_rule_runtime,apply_rule_discard_result,3,[{file,"emqx_rule_runtime.erl"},{line,65}]},{emqx_rule_runtime,apply_rules,3,[{file,"emqx_rule_runtime.erl"},{line,61}]},{emqx_rule_events,on_message_publish,2,[{file,"emqx_rule_events.erl"},{line,142}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,200}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,180}]},{emqx_broker,publish,1,[{file,"emqx_broker.erl"},{line,219}]},{emqtt,eval_msg_handler,3,[{file,"emqtt.erl"},{line,1824}]},{emqtt,deliver,3,[{file,"emqtt.erl"},{line,1802}]},{emqtt,publish_process,4,[{file,"emqtt.erl"},{line,1684}]},{gen_statem,loop_state_callback,11,[{file,"gen_statem.erl"},{line,1426}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, rule_id: <<"par-kafka-forward">>

</details>

In the emqx dashboard test gui we get the following error when testing the rule:
400 BAD_REQUEST: {"select_and_transform_error":"jq_exception"}

This is a test payload which should pass the rule, and does so in version 5.1.0:

`{
  "mailpieceId":"1659913515",
  "imageKey":"13546546331",
  "timestamp":"2023-08-17T11:12:23.619+02:00",
  "sourceId":"ACS12",
  "mpAttr":{
    "type":"PARCEL",
    "preknowledge":{
      "barCodes":[
        {"type":"DATA_MATRIX","value":"756993713025401963481","status":"DETECTED_AND_RECOGNIZED"},
        {"type":"DATA_MATRIX","value":"7560509","status":"DETECTED_AND_RECOGNIZED"}
      ]
    }
  }
}`

### What did you expect to happen?

The rule should be able to map the data as it does in version 5.1.0

### How can we reproduce it (as minimally and precisely as possible)?

Use the above rule and test payload to test it out in the emqx dashboard

### Anything else we need to know?

Funny thing, when we move the problematic jq select line on the first position, the rule is working again:

SELECT
     jq('.mpAttr.preknowledge.barCodes[] | (if .type == "DATA_MATRIX" and .status == "DETECTED_AND_RECOGNIZED" and 
      select(.value | startswith("756")) then . else empty end)', payload) as payload.scanned.barcodes,
      payload.mailpieceId,
      payload.timestamp as payload.scanned.timestamp,
      payload.sourceId as payload.scanned.sourceId,
      payload.imageKey as payload.scanned.imageKey,
      substr(payload.imageKey, 0, 6) as payload.scanned.postcode6
    FROM
      "bridge/par-atg-kafka/#"
   

### EMQX version

<details>
sysdescr  : EMQX Enterprise
version   : 5.1.1
datetime  : 2023-08-17T11:24:17.978793490+00:00
uptime    : 2 days, 3 hours, 48 minutes, 51 seconds
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux xxxx.x86_64 #1 SMP Tue Jun 27 21:48:55 UTC 2023 x86_64 GNU/Linux
```
</details>

**Comment by kjellwinblad** [comment]
Thanks for reporting this. I think the reason why this worked in 5.1.0 was due to a bug that existed then but that has been fixed in 5.1.1 (probably in this PR https://github.com/emqx/emqx/pull/11260).

The way the rule engine SQL works when overriding fields in the original input is currently not documented. This is unfortunate but something that we are actively working on so you can expect the documentation to improve soon. You can see the sequence of `SELECT` fields as a sequence of variable assignments. If you write for example `SELECT payload.a as payload.b, payload as p` the output field p will be an "object" containing only the field b (note that the field a from the input payload is gone). The reason why the SQL above works at all is because the SQL language interpreter currently looks for a field that is not found in the output field in the corresponding input field before it gives up (we might remove this feature in a future release as it can be quite confusing). If you want to "change" the input payload it is therefore recommend to start by saving the original payload under a different name. So your rule can be rewritten to the following (I took the liberty to reformat the jq expression into multiple lines as well):

```
SELECT
json_decode(payload) as input_payload,
input_payload.mailpieceId as payload.mailpieceId,
input_payload.timestamp as payload.scanned.timestamp,
input_payload.sourceId as payload.scanned.sourceId,
input_payload.imageKey as payload.scanned.imageKey,
substr(input_payload.imageKey, 0, 6) as payload.scanned.postcode6,
jq('
   .mpAttr.preknowledge.barCodes[] |
   (if .type == "DATA_MATRIX" and
       .status == "DETECTED_AND_RECOGNIZED" and
       select(.value | startswith("756"))
    then
      .
    else
      empty
    end)',
    input_payload) as payload.scanned.barcodes
FROM
"bridge/par-atg-kafka/#"
```

Note that you will also get the temp field `input_payload` but this usually does not matter since you can select what data you want to forward in the payload template for MQTT forward action or the template sting for the bridges.

Please let us know if this solves your issue.
