### ISSUE TITLE
Hi,I got a problem that make mqtt can't connect. 你好，我遇到一个问题导致mqtt无法连接

### ISSUE THREAD

**Issue by zhangkaqiu520** [emqx/emqx#11777]
### What happened?

i see a message in my docker container logs just like this "[error] dropped: 1, ine: 735,mfa: emgx_resource _worker:append _queue/4, msg: drop_query,reason: queue full" i don't know what's mean about "queue_full"

我在docker容器中看到一条日志，从这条日志开始 mqtt无法正常链接，报错中提到了队列满，但是我无法得知是什么队列满了

### What did you expect to happen?

i see a message in my docker container logs just like this "[error] dropped: 1, ine: 735,mfa: emgx_resource _worker:append _queue/4, msg: drop_query,reason: queue full" i don't know what's mean about "queue_full"

我在docker容器中看到一条日志，从这条日志开始 mqtt无法正常链接，报错中提到了队列满，但是我无法得知是什么队列满了

### EMQX version

<details>

```console
emqx:5.0.14
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Hi @zhangkaqiu520 

It seems you have configured data integration (mqtt or http),
and the buffer queue is full maybe due to the integration is not healthy.

This is just an error level log saying that the queue is full so it needs to drop data,
but the log itself is not directly connected to client disconnect.

To understand better why the clients disconnect, we will need to see more logs,
and preferably inspect the bridge configs too.
 
You can also try:
* Disable the data bridge to see if it makes a difference.
* Change to `async` mode of the bridge (I am not sure if there is an async mode though because I don't know which integration you are using)
* Upgrade to newer version e.g. v5.3.0
