### ISSUE TITLE
cannot set Max Packet Size more that 256M

### ISSUE THREAD

**Issue by onlineapps-cloud** [emqx/emqx#11894]
### What happened?

i cannot set set Max Packet Size more that 256M

### What did you expect to happen?

I expect to set more that 256M, because in front end i have option to set more, why not working?
![image](https://github.com/emqx/emqx/assets/69077240/e067e70b-a959-4e11-b755-2d8eda7ed859)

### EMQX version

v5.2.1

### Log files

`400 BAD_REQUEST: [{"value":1073741824,"reason":{"reason":"max_mqtt_packet_size_too_large","maximum":"256M"},"path":"mqtt.max_packet_size","kind":"validation_error"},{"value":"","reason":"not_a_enum_symbol","path":"mqtt.shared_subscription_strategy","kind":"validation_error"}]`

**Comment by ieQu1** [comment]
256 MB is the maximum theoretical size of the MQTT packet: https://www.emqx.com/en/blog/best-practices-of-maximum-packet-size-in-mqtt
This limit is implicitly imposed by the standard, because size of the packet is encoded as a Variable Byte Integer type, which can only encode values up to 268,435,455: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011

EMQX provides an extension to the protocol that allows to split larger payloads into multiple MQTT packets and reassemble them: https://docs.emqx.com/en/enterprise/latest/file-transfer/introduction.html

**Comment by onlineapps-cloud** [comment]
this feature is implemented in enterprise version, i correct understand? because link that you give, is assigned to enterprise documentation, i suggest you to add information in emqx dashboard near on select file size, for future users, to understand that this feature is available in enterprise version.

**Comment by ieQu1** [comment]
Yes, this is a feature of the Enterprise Edition.
