### ISSUE TITLE
SQL Test cannot run when a field's value is null

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12364]
### What happened?

Payload:

```
{
  "msg": null
}
```

SQL:

```
SELECT
    payload.msg as msg
FROM
    "t/#"
```

Nothing happens when I click `Run Test`

### What did you expect to happen?

SQL Test should output:

```
{
  "msg": null
}
```

### EMQX version

EMQX v5.4.1

### OS version

macOS 12

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
I don't think it is a bug.

NULL is no value. 

User should use `is_null` to handle that.

**Comment by tigercl** [comment]
@qzhuyan If I send a real message directly with the same Payload, this SQL will be triggered. The behavior of both parties is different, so there is a problem with one party?

And, there's nothing to suggest that SQL shouldn't handle null values.

**Comment by ysfscream** [comment]
@tigercl Thank you for reporting this issue. Your problem is an error in our Dashboard when handling `null` values. We have acknowledged this and plan to address it in the upcoming release of EMQX v5.5.0.

<img width="1137" alt="image" src="https://github.com/emqx/emqx/assets/21299158/a2fd9934-0282-4c8f-a60f-ec02dfa1b75d">

**Comment by ysfscream** [comment]
@tigercl Fixed in Dashboard PR: https://github.com/emqx/emqx-dashboard5/pull/2370

<img width="1295" alt="image" src="https://github.com/emqx/emqx/assets/21299158/1217e60b-9af0-4e3b-b673-f78e2ed6f587">
