### ISSUE TITLE
If username is not set in SQL Test, the default value of username is an empty string

### ISSUE THREAD

**Issue by tigercl** [emqx/emqx#12365]
### What happened?

If `username` is not set in SQL Test, the default value of `username` is an empty string: `""`.

If I use MQTTX and `username` is not set when connecting, `username` will be `undefined`. This means that I cannot simulate this situation in SQL Test.

### What did you expect to happen?

If `username` is not set in SQL Test, then it should be `null` in the HTTP request of SQL Test, note that it is not a string.

### EMQX version

EMQX v5.4.1

### OS version

macOS 12

### Log files

<details>

</details>

**Comment by ysfscream** [comment]
@tigercl

Thank you for highlighting this issue. Our EMQX SQL Test treats an unset username as an empty string (`""`) following our API standards. This differs from MQTTX, where an unset field might be `null`.

<img width="892" alt="image" src="https://github.com/emqx/emqx/assets/21299158/5d6e3d43-1fdb-4d13-870b-07878d8e5e91">

To clarify, it's our design that if the username is set to an empty string in the SQL Test, the result is `undefined`. This approach is consistent with our data type specifications and is not a bug. 

<img width="1196" alt="image" src="https://github.com/emqx/emqx/assets/21299158/a9f388c6-04ff-4d75-bc20-b897670a3b41">

If you have encountered any specific or complex testing scenarios where using null instead of an empty string for username would be more appropriate, your feedback would be invaluable.

**Comment by tigercl** [comment]
I don't know how you get this output, if I set Username to empty in SQL Test, the output I get is an empty string:

<img width="1920" alt="image" src="https://github.com/emqx/emqx/assets/15085956/a72fdad6-92e3-4e3e-9f1c-f682c3968ed0">

**Comment by ysfscream** [comment]
This output resulted from the JSON parse in the dashboard, which has now been corrected. It indeed return a empty string for test result.

<img width="1207" alt="image" src="https://github.com/emqx/emqx/assets/21299158/b29c95c5-768a-4ee3-8119-051e56d48c5a">

But as I said, the username data type is set as a string in the API, so we cannot pass null or undefined values for it. Maybe we should consider incorporating this into the rule test enhancement requirements. @wivwiv

**Comment by ysfscream** [comment]
This output resulted from the JSON parse in the dashboard, which has now been corrected. It indeed returns an empty string for test result.

<img width="1207" alt="image" src="https://github.com/emqx/emqx/assets/21299158/b29c95c5-768a-4ee3-8119-051e56d48c5a">

But as I said, the username data type is set as a string in the API, so we cannot pass null or undefined values for it. Maybe we should consider incorporating this into the rule test enhancement requirements. @wivwiv

**Comment by ysfscream** [comment]
This output resulted from the JSON parse in the dashboard, which has now been corrected. It indeed returns an empty string for test result.

<img width="1207" alt="image" src="https://github.com/emqx/emqx/assets/21299158/b29c95c5-768a-4ee3-8119-051e56d48c5a">

But as I said, the username data type is set as a string in the API, so we cannot pass null or undefined values for it. Maybe we should consider incorporating this into the rule test enhancement requirements. @wivwiv

**Comment by ysfscream** [comment]
This output resulted from the JSON parse in the dashboard, which has now been corrected. It indeed return a empty string for test result.

<img width="1207" alt="image" src="https://github.com/emqx/emqx/assets/21299158/b29c95c5-768a-4ee3-8119-051e56d48c5a">

But as I said, the username data type is set as a string in the API, so we cannot pass null or undefined values for it. Maybe we should consider incorporating this into the rule test enhancement requirements. @wivwiv
