### ISSUE TITLE
How to list all the topics in dashboard? 

### ISSUE THREAD

**Issue by SmartSystemElectronics** [emqx/emqx#12815]
### What happened?

I created 2 clients and I can communicate with each other, but can't the topics I created be created automatically in the dashboard? When I create this topic on the dashboard myself, I can monitor incoming and outgoing data, but when the application goes into the field, there will be too many devices and there will be a topic per device. Will I need to create a separate topic for each of them myself via the dashboard?

### What did you expect to happen?

All topics have not listed on dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

I use MQTTX desktop for dashboard.

**Comment by ieQu1** [comment]
Hello,

You don't need to explicitly create topics in the dashboard. By design, topics in EMQX are ephemeral. EMQX follows a subscriber-centric design: when the broker receives a PUBLISH packet from a client, it searches for the clients that subscribe to the matching topic filter, and routes the message to them or drops the packet when there are no subscribers. All of this is done dynamically, no explicit configuration is needed.

There is an optional feature that allows to collect per-topic _statistics_. I believe this is what you created in the dashboard. This is needed because by default EMQX doesn't keep such statistics: there could be 100s of millions of topics, just maintaining counters for each of them would be extremely wasteful in terms of RAM. Instead, we allow users to selectively monitor certain topics.
