### ISSUE TITLE
peer_cert_as_username when using proxy protocol v2

### ISSUE THREAD

**Issue by ViktorWb** [emqx/emqx#12840]
### What happened?

Hi! I'm trying to setup EMQX in Kubernetes, and I want to use client certificate authentication. I'm reading that it should be poosible to overwrite the username with the client certificate common name. I'm terminating mTLS in a load balancer which is forwarding the connection to EMQX. When forwarding, it is using proxy protocol v2 to provide the source IP and client certificate common name to EMQX.

I am using configuration
```
listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
  proxy_protocol = true
}
mqtt {
  peer_cert_as_clientid = "disabled"
  peer_cert_as_username = "cn"
}
```

EMQX is correctly parsing the source IP from the proxy protocol v2 header, because I can see that the IP address is correctly showing the source IP in the dashboard. However, the username does not get updated. Instead, the original username as provided by the client is used.

I am checking the client username on the dashboard, at `/#/clients/detail/<client-id>`.

Is it possible to use `peer_cert_as_username` when using the proxy protocol, or only for TLS connections that are decrypted by EMQX?

### What did you expect to happen?

I expected the username to be changed to the common name of the certificate, as provided to EMQX over the proxy protocol. The username does not get changed. Instead, the original username as provided by the client is used.

### How can we reproduce it (as minimally and precisely as possible)?

The following is an example proxy v2 protocol header, encoded as base64. It contains the source IP + port, as well as information about the client certificate, including the common name. Start an EMQX server with the configuration above, connect a TCP client on port 1883, send the header (decode the base64), and then run a normal MQTT client on the TCP connection.

`DQoNCgANClFVSVQKIREAcFP7wPYiJIc8u64HWyAABQcAAAAAIQAHVExTdjFfMyIAHnRlc3QtdXNlcm5hbWUtZnJvbS1jb21tb24tbmFtZSMAG0VDREhFLVJTQS1BRVMxMjgtR0NNLVNIQTI1NiQABlNIQTI1NiUAB1JTQTIwNDg`

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.1.6
datetime  : 2024-04-05T19:31:02.585680173+00:00
uptime    : 6 minutes, 42 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux emqx-core-6d89c987d6-0 5.15.133+ #1 SMP Sat Dec 30 13:01:38 UTC 2023 x86_64 GNU/Linux
```

</details>

**Comment by zmstone** [comment]
The proxy might not be strictly following the spec?
It should send type [`32` (`0x20`)](https://github.com/emqx/esockd/blob/09782149d22918f14f9fc402d44d4a3eb3973b16/src/esockd_proxy_protocol.erl#L50) and subtype [`34`(`0x22`)](https://github.com/emqx/esockd/blob/09782149d22918f14f9fc402d44d4a3eb3973b16/src/esockd_proxy_protocol.erl#L52)

However the raw bytes you shared has type (not subtype) `34`, which is unknown to EMQX.

Tried to send the raw bytes you provided and traced the ppv2 header parse results as below
```
                                   {proxy_socket,inet4,#Port<0.58>,
                                    {83,251,192,246},
                                    {34,36,135,60},
                                    48046,1883,
                                    [{pp2_ssl,
                                      [{pp2_ssl_client,true},
                                       {pp2_ssl_client_cert_conn,true},
                                       {pp2_ssl_client_cert_sess,true},
                                       {pp2_ssl_verify,success}]},
                                     {{pp2_raw,33},<<"TLSv1_3">>},
                                     {{pp2_raw,34},
                                      <<"test-username-from-common-name">>},
                                     {{pp2_raw,35},
                                      <<"ECDHE-RSA-AES128-GCM-SHA256">>},
                                     {{pp2_raw,36},<<"SHA256">>},
                                     {{pp2_raw,37},<<"RSA2048">>}]}}
```

For compare, my test (see details at the end of this post) is traced as below:
```
% 08:30:44 <0.5223.0>({emqx_connection,init,4})
% esockd_proxy_protocol:parse_v2(1, 1, <<172,19,0,1,172,19,0,4,180,156,34,179,32,0,24,7,0,0,0,0,33,0,7,84,76,83,118,
  49,46,51,34,0,6,67,108,105,101,110,116>>, {proxy_socket,inet4,#Port<0.60>,undefined,undefined,undefined,undefined,[]})

% 08:30:44 <0.5223.0>({emqx_connection,init,4})
% esockd_proxy_protocol:parse_v2/4 -> {ok,
                                       {proxy_socket,inet4,#Port<0.60>,
                                        {172,19,0,1},
                                        {172,19,0,4},
                                        46236,8883,
                                        [{pp2_ssl,
                                          [{pp2_ssl_client,true},
                                           {pp2_ssl_client_cert_conn,true},
                                           {pp2_ssl_client_cert_sess,true},
                                           {pp2_ssl_verify,success},
                                           {pp2_ssl_version,<<"TLSv1.3">>},
                                           {pp2_ssl_cn,<<"Client">>}]}]}}

```

Tested with this script: https://github.com/emqx/emqx/blob/v5.6.0/scripts/test/start-two-nodes-in-docker.sh
and patched with:
```
--- a/scripts/test/start-two-nodes-in-docker.sh
+++ b/scripts/test/start-two-nodes-in-docker.sh
@@ -84,6 +84,7 @@ docker run -d -t --restart=always --name "$NODE1" \
   -e EMQX_listeners__wss__default__enable=false \
   -e EMQX_listeners__tcp__default__proxy_protocol=true \
   -e EMQX_listeners__ws__default__proxy_protocol=true \
+  -e EMQX_mqtt__peer_cert_as_username=cn \
   "$IMAGE1"

 docker run -d -t --restart=always --name "$NODE2" \
@@ -98,6 +99,7 @@ docker run -d -t --restart=always --name "$NODE2" \
   -e EMQX_listeners__wss__default__enable=false \
   -e EMQX_listeners__tcp__default__proxy_protocol=true \
   -e EMQX_listeners__ws__default__proxy_protocol=true \
+  -e EMQX_mqtt__peer_cert_as_username=cn \
   "$IMAGE2"

 mkdir -p tmp
````

To trace the parse functions your self:
- run `emqx remote_consol`
- in erlang console, evaluate this expression `redbug:start("esockd_proxy_protocol:parse_v2 -> return",[{msgs,1000},{time,60000}]).`
- this will give you 60 seconds to observe the inputs and outputs of ppv2 parse function.

**Comment by ebrjens** [comment]
Hi! I ran into the same issue with a similar setup.
As a further note: The [Ingress Nginx Proxy Protocol](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/exposing-tcp-udp-services.md) was used.
Regardless of whether the Nginx protocol was not implemented correctly, this problem cannot be recognized at first glance. If the username corresponds to the CN, everything works as expected.

This bug is a critical security vulnerability. It allows impersonation.
In my opinion, a connection can be denied because of an incorrect proxy protocol implementation. But it must not be possible to bypass the security functions. Nobody realizes that there is a security gap without trying it out.

**Comment by zmstone** [comment]
EMQX listener is configured with proxy-protocol, and should only be exposed to the proxy which support PPV2.
If the listener is wide open towards the internet and can be accessed by a malicious client, that's a critical security issue in one's firewall/security-group configuration, not EMQX to blame.

**Comment by ebrjens** [comment]
Access was of course via the proxy. (Otherwise it probably wouldn't work at all.) There's even a firewall in front of it. And this is of course accessible from the Internet, as we want to communicate with IoT devices.
The problem: The broker operator is not aware that its proxy (Ingress NGINX) is not PPV2 compliant. It is not obvious because everything works as long as the username matches the CN. 

The [documentation](https://docs.emqx.com/en/emqx/v5.7/deploy/cluster/lb.html#real-ip-and-proxy-protocol) also says nothing about the requirement of PPV2.
V1 is also [mentioned](https://docs.emqx.com/en/emqx/v5.7/gateway/stomp.html#add-listeners): "Proxy Protocol: Set to enable protocol V1/2 if EMQX is configured behind the load balancer"

And somewhere in the code hidden is the comment: `CN` is unsupported in Proxy Protocol V1

I believe the authorization mechanism should be resilient to external factors (due to misconfiguration of an LB or invalid protocol versions). Better to deny connection in such cases. (Better safe than sorry)

**Comment by zmstone** [comment]
Hi @ebrjens 

Some clarifications from me:
- You can to comment in a thread which focused on malformed PPV2 (but not V1) headers. This made me thought that your concern was about clients bypassing TLS and access TCP listener directly.
- I do not agree this is a "critical" security issue of EMQX because it's clearly a misconfiguration. A negative test should find the authorization issue.

I agree things can be improved in EMQX to apply more strict check of PPv2 --- not as a commitment to support it anytime soon though.
I also agree, documents can be made more clear about PPv2.

For authorization, you should not need to use peer_cert_as_xxx, just use `${cert_common_name}` in the ACL rules.

For client integrity check, in EMQX Enterprise, we will add clientinfo based authentication.
It can validate the client properties (e.g. clientid, username) against cert info (e.g. CN, UT in DN etc).
e.g. A client must use certificate common name as its `username`, otherwise EMQX will reject.

**Comment by zmstone** [comment]
doc PR: https://github.com/emqx/emqx-docs/pull/2565

**Comment by zmstone** [comment]
taking a look in the original post again, it was indeed not proxy protocol v1,
it's sent with a `QUIT` signature, so it is indeed a malformed v2 header.
v1 header should have a `PROXY` signature

**Comment by ebrjens** [comment]
Thanks for updating the docs with hint to the V2 version. (Honestly, I don't even know if it's the V1 version or a protocol error. There is nothing in the Ingress NINGX documentation.)
EMQX supports the deployments in K8s. And the Ingress NGINX used is one of the three by Kubernetes supported and maintained ingress controllers (besides AWS and GWC).
So, I think this is common setup where you don’t expect an incompatibility that results in a security issue.

`${cert_common_name}` is not supported in the ACL and does therefore not solve this problem.

**Comment by zmstone** [comment]
> `${cert_common_name}` is not supported in the ACL and does therefore not solve this problem.

It's allowed in http, postgres, mysql, redis, and mogodb,
For other authorization backends, starting from 5.7, one can extract `cn` to `client_attrs`,  and use `${client_attrs.cert_cn}` in ACL rule templates.
e.g.
```
mqtt.client_attrs_init = [
  { 
    expression = cn
    set_as_attr = cert_cn
  }
]
```

**Comment by ebrjens** [comment]
The "client_attrs" could be an authorization workaround for an ACL when peer_cert_as_username is not working with this proxy protocol issue. The username might still be invalid. The missing "clientinfo-based authentication" that you mentioned is indeed an important feature that mTLS authentication lacks. Rejecting clients directly on connect because they are impersonating someone else is missing.
