### ISSUE TITLE
Get acknowledgement from subscriber(s) after publish messages

### ISSUE THREAD

**Issue by KaeYan93** [emqx/emqx#13008]
### What would you like to be added or enhanced?

Hi EMQX team,

Is there a way for publisher to get the acknowledgments from subscriber(s)? Let say the publisher expect 2 acks from 2 subscribers

Is my understanding correct that the QoS 2 only guarantees the message reaching to broker, but not necessary the subscribers right?

### Why is this needed?

This is for the publisher to ensure the subscribers has received the message, and that it is not part of application code to implement this acknowledgement.

**Comment by kjellwinblad** [comment]
> Is my understanding correct that the QoS 2 only guarantees the message reaching to broker, but not necessary the subscribers right?

Your understanding is correct. 

> Is there a way for publisher to get the acknowledgments from subscriber(s)? Let say the publisher expect 2 acks from 2 subscribers

As far as I know, there is currently no such functionality. So, right now, I think you will have to relay on application logic to get such acknowledgments.

Perhaps, this is an extension that could be worth implementing in the feature. Can you explain why you need this to be implemented as part of EMQX rather than with application logic?

**Comment by zmstone** [comment]
In MQTT, there is no builtin semantics for consumer confirmation. The specification however provided guidelines how to implement it, check out request/response:
https://www.emqx.com/en/blog/mqtt5-request-response
