### ISSUE TITLE
bad_cert,hostname_check_failed

### ISSUE THREAD

**Issue by Echolpl** [emqx/emqx#13360]
### What happened?

2024-06-28T05:56:16.615883+00:00 [error] Ekka(AutoCluster): Discovery error: {failed_connect,[{to_address,{"192.168.16.38",6443}},{inet,[inet],{tls_alert,{handshake_failure,"TLS client: In state wait_cert at ssl_handshake.erl:2150 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}"}}}]}

Guessing the impact of Erlang/OTP 26 version！！！

### What did you expect to happen?

When using emqx/emqx: 5.7.1 image version to create a three node cluster on k8s, the cluster cannot be automatically created, and the container error log is as follows:

EMQX 5.7.1 is running now!
2024-06-28T05:56:16.615883+00:00 [error] Ekka(AutoCluster): Discovery error: {failed_connect,[{to_address,{"192.168.16.38",6443}},{inet,[inet],{tls_alert,{handshake_failure,"TLS client: In state wait_cert at ssl_handshake.erl:2150 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}"}}}]}

### Anything else we need to know?

Guessing the impact of Erlang/OTP 26 version！！！
Container image Erlang/OTP version 25 is available

### EMQX version

EMQX 5.7.1

### Log files

2024-06-28T05:56:16.615883+00:00 [error] Ekka(AutoCluster): Discovery error: {failed_connect,[{to_address,{"192.168.16.38",6443}},{inet,[inet],{tls_alert,{handshake_failure,"TLS client: In state wait_cert at ssl_handshake.erl:2150 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}"}}}]}

**Comment by qzhuyan** [comment]
what do you mean on this ?

> Container image Erlang/OTP version 25 is available


I think our CI should catch it, are you using our official docker image or you build on your own?

**Comment by Echolpl** [comment]
> official docker



> what do you mean on this ?
> 
> > Container image Erlang/OTP version 25 is available
> 
> I think our CI should catch it, are you using our official docker image or you build on your own?

official docker image. it's emqx/emqx:5.7.1

**Comment by qzhuyan** [comment]
Does your certificate use wildcard CName? 
Would be helpful if you could share your node certificate.

**Comment by zmstone** [comment]
## Quick answer
given that 6443 is likely k8s api service port.

I supposed you can:
1. delete "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt".
2. provide a certificate which is issued for the api server hostname. I can see that in your case it's actually an IP addresses in use 192.168.16.38, maybe assign a hostname or DNS (like @qzhuyan suggested above).
 
## Details
There is indeed a non-compatible change from OTP 25 to OTP 26 in TLS.
OTP 25: SSL handshake does not check hostname unless `verify_peer` is explicitly set.
OTP 26: SSL handshake checks hostname by default.

In your case, I guess it hits this line: https://github.com/emqx/ekka/blob/7dd7ba7a465cb56b9b8718e32fef5564ba7f851d/src/ekka_cluster_k8s.erl#L88
which means: you have configured a CA certificate to verify server certificate, hence HTTP client in EMQX will try to verify the hostname in the certificate against the real hostname in use (192.168.16.38).

It was not check on OTP 25 due to the old default value --- we can consider it a bug in the older version.

I will close this issue because I do not believe it is a bug.
However, if the recommended fixes did not work for you, you are welcome to reopen this issue, or open a new issue.

**Comment by Echolpl** [comment]
> ## Quick answer
> given that 6443 is likely k8s api service port.
> 
> I supposed you can try either of below:
> 
> 1. delete "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt".
> 2. provide a certificate which is issued for the api server hostname.
> 3. Assign a hostname or DNS (like @qzhuyan suggested above) for the API service endpoint, I can see that in your case it's actually an IP addresses in use 192.168.16.38.
> 
> ## Details
> There is indeed a non-compatible change from OTP 25 to OTP 26 in TLS. OTP 25: SSL handshake does not check hostname unless `verify_peer` is explicitly set. OTP 26: SSL handshake checks hostname by default.
> 
> In your case, I guess it hits this line: https://github.com/emqx/ekka/blob/7dd7ba7a465cb56b9b8718e32fef5564ba7f851d/src/ekka_cluster_k8s.erl#L88 which means: you have configured a CA certificate to verify server certificate, hence HTTP client in EMQX will try to verify the hostname in the certificate against the real hostname in use (192.168.16.38).
> 
> It was not checked when running on OTP 25 due to the old default value --- we can consider it a bug in the older version.
> 
> I will close this issue because I do not believe it is a bug. However, if the recommended fixes did not work for you, you are welcome to reopen this issue, or open a new issue.

I have successfully solved this problem, thank you for your answer! This is not a bug！
OTP 26:EMQX_CLUSTER__K8S__APISERVER must be a domain name rather than an IP.
