### ISSUE TITLE
为啥不用golang开发，emqx启动太慢了，每次启动都要半分钟，等的花都谢了

### ISSUE THREAD

**Issue by icetech233** [emqx/emqx#13857]
### What would you like to be added or enhanced?

为啥不用golang开发，emqx启动太慢了，每次启动都要半分钟，等的花都谢了

### Why is this needed?

为啥不用golang开发，emqx启动太慢了，每次启动都要半分钟，等的花都谢了

**Comment by terry-xiaoyu** [comment]
It should be get started within 10s, it would be a problem if not.

**Comment by qzhuyan** [comment]
30s is abnormal. which version? OS?

**Comment by icetech233** [comment]
> 30s is abnormal. which version? OS?

ubuntu 2204

**Comment by icetech233** [comment]
> It should be get started within 10s, it would be a problem if not.

I hope to complete all the startups within 1 second

**Comment by zmstone** [comment]
tested with docker on my shitty local dev machine:

```
# takes about 10s to boot
docker run --rm -it --cpuset-cpus="0" --net emqx.io emqx/emqx:5.8.0 emqx console
# takes about 5s to boot
docker run --rm -it --cpuset-cpus="0,1,2,3" --net emqx.io emqx/emqx:5.8.0 emqx console
```

we do not have plan to implement EMQX using golang, so I am going to close this issue here.
If you wish to help improving EMQX, I would recommend to create a new issue with a less insulting title
and more constructive information.

1. Hardware or VM profile, CPU/ram etc.
2. Maybe try `env DEBUG=1 emqx console | ts` (`| ts` is to add a timestamp to each debug output, you can install with `sudo apt install moreutils` on Ubuntu)
3.
