### ISSUE TITLE
why docker -v not work 

### ISSUE THREAD

**Issue by yuchao-wang** [emqx/emqx#13893]
### What happened?

docker volume not work ? but other docker images volume work success

the emqx_auth_redis.conf on the host and emqx_auth_redis.conf in the container are not the same one ? why ?

if you change the file on the host , the file in the container do not synchronize change ,  i dont konw why

I operate like that

# i am root permission
docker volume rm wangyuchao
docker volume create wangyuchao
docker volume inspect wangyuchao
chmod 777 /var/lib/docker/volumes/wangyuchao/
docker run -d --name wangyuchao -p 9880:1883 -p 9881:8083 -p 9882:8084 -p 9883:8883 -p 9884:18083 -v wangyuchao:/opt/emqx/ emqx/emqx

# look up the file on the host , inode is 1311937
stat /var/lib/docker/volumes/wangyuchao/_data/etc/plugins/emqx_auth_redis.conf

# container, inode is 1314153
docker exec -it wangyuchao /bin/bash
stat /opt/emqx/etc/plugins/emqx_auth_redis.conf 

look ! the two file Inode are not the same one, it is really crazy !!! But 

![WechatIMG34](https://github.com/user-attachments/assets/3cf4b7bc-ea69-4143-84b6-0c5669b5e06c)

### What did you expect to happen?

emqx_auth_redis.conf on the server and emqx_auth_redis.conf in the container is the same file 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment]
I followed the instruction, but I cannot reproduce this problem. If I had to make a wild guess, it has to do with docker's usage of overlayfs. Note that you've mounted the volume into `/opt/emqx` directory that contains files from the container's RootFS layers. While I can't reproduce it locally (perhaps due to different version of docker deamon), I can speculate that such mount MAY activate some sort of CoW behavior when file is written from inside the container.

But regardless, this is a pure docker problem, not EMQX problem. It's better to ask this question to Docker community.
