### ISSUE TITLE
Request to Enable Core-Replicant Architecture in EMQX Community Edition

### ISSUE THREAD

**Issue by hoptical** [emqx/emqx#14239]
### What would you like to be added or enhanced?

We have been utilizing the [core-replicant architecture](https://docs.emqx.com/en/emqx/latest/deploy/cluster/mria-introduction.html#enable-core-replicant-mode) in EMQX version 5.4 and found it instrumental for our deployment. However, with the latest updates, this feature is now only available in the Enterprise edition. This change presents a significant challenge for us as it necessitates either adopting a masterless design for high-load production environments or remaining on version 5.4.

We kindly request that you consider making the core-replicant architecture available in the community edition. 

### Why is this needed?

This architecture offers a fundamental design pattern that benefits a wide range of environments, including those with lower loads. Its availability would greatly enhance the scalability and reliability of EMQX for community users.

Thank you for considering this request. We believe it would add significant value to the community edition and support a broader user base.

**Comment by gujun720** [comment]
Hi @hoptical ,

Thank you for your affinity and concern for the EMQX project.

In the EMQX 5.8 release, we made several feature adjustments between the EMQX open-source project and the EMQX Platform (the commercial product). Since 5.8, the cluster option for the open-source edition (AKA community edition) is the masterless cluster.

We have been developing the EMQX open-source project for a decade. EMQ's vision is to build up the best MQTT platform for emerging IoT scenarios. We believe in the value of open source, and switching to a proprietary license is NOT an option on our list.

We are struggeling to ensure the sustainability of the EMQ company and the EMQX project, we need to deliver enterprise-grade features to paid customers and enhance the EMQX Platform's business value. It's challenging to differentiate the commercial version while maintaining the competence of the open-source version. We adjusted the features related to **advanced clustering** and **usability** in the EMQX project. We will also continuously enhance the existing enterprise data integration and security features.

**Advanced clustering** features include cluster linking, cluster-level durable sessions, core-replica architecture, etc. **Usability** features include the graphic user interface (dashboard) and observability.


Thanks.
Jun

**Comment by ennc0d3** [comment]
As this is a breaking change, I would at least expected a note in the release https://docs.emqx.com/en/emqx/latest/changes/changes-ce-v5.html#_5-8-0, which I didn't find either. We are also using replicas and this came as an surprise.

Thanks,

**Comment by ieQu1** [comment]
As @gujun720 said, profitability of the enterprise edition is crucial for the continued development of the open source edition. Choices like this are not easy, but in the end they serve everyone's interest.
