### ISSUE TITLE
开源版设置集群,无法组网

### ISSUE THREAD

**Issue by xyZangGit** [emqx/emqx#14235]
#### Environment

- OS: 
- centerOS7
- Erlang/OTP: 
- EMQ: 
- [5.8.2 (Open Source)]

#### Description

按照文档进行 discovery_strategy = static 集群模式，但是一直不能发现节点
1883 4370 5370 5369 端口也都放开了，两个节点的服务器网络互相也能ping通
![42fc8d7f5758b717494f102233dad3a](https://github.com/user-attachments/assets/83fc6dde-709a-4690-aa1f-772017ff3ce6)

![bd090da77b89f00df062b8b597627de](https://github.com/user-attachments/assets/fcd36b10-e7f7-445c-8d34-2dfcf7f2a5bc)
这个是日志：
![image](https://github.com/user-attachments/assets/c8ad121b-6d73-4d8c-8c1b-98556faea2e2)

**Comment by zmstone** [comment]
@xyZangGit 为了方便社区里遇到同样问题的人好搜索，报issue最好是用英文。然后配置和日志复制粘贴文本，不要截屏。

Maybe it's because port `4371` (for node `emqx1`) and `4372` (for node `emqx2`) are not reachable.
Recommend to use `emqx` as node names for both nodes, so they both listen on port `4370`.

Port mapping rule is defined here:
https://docs.emqx.com/en/emqx/latest/deploy/cluster/security.html#port-mapping
