### ISSUE TITLE
ROBOT attack vulenrability

### ISSUE THREAD

**Issue by aravindranathan** [emqx/emqx#1521]
#### Environment

- OS:  Ubuntu 14.04
- Erlang/OTP:  19.0
- EMQ: 2.2.0

#### Description

Erlang is affected by the ROBOT attack vulnerability including versions 19.0 which is used to build EMQ. Will there be an EMQ build that's built by an Erlang version that's beyond 19.3.6.4 or 20.2?

A solution disabling TLS_RSA ciphers exist but so is the solution of building EMQ using a new build of the erlang.

ROBOT test tool
https://github.com/drwetter/testssl.sh

**Comment by emqplus** [comment]
@aravindranathan All the EMQ R2.3+ releases are built on Erlang/OTP R20+. Thanks for the security report. @huangdan @zhengyupan Please verify the issue using the ROBOT test tool.

**Comment by zhengyupan** [comment]
Hi @aravindranathan ，
This issue is fixed in the 3.0 beta, tested using https://github.com/devsecur/robot-attack , result:
 ./robot-detect.py -p 8883  18.xx.xx.xx
Scanning host 18.224.109.239 ip 18.xx.xx.xx port 8883
RSA N: 0xd43bf90bddaaf75aca293c5d76a807fe7300c792518923126c8dda195e023594f11ed56d505f06ff1bfb727fa163d89f020f96dfb118c3c407a6148055ac5c25ba70a4f86b3ac51eefcf3e0e1689e88f8a6695eaee2d0acd63f6c76b658df7b39d212c97ce13a00f049aaa86e71749ff7f4331fbdb1d1cede9f0b341dc95d4c81a700cdaff4d37c06f8a5b404bb72c5e29eeec9dd5e2e12b35314a25b32ad8c1d4460e6c0f3b7d9bb4b41259886ba3b85888eed7f8a9629eb80a116bf717920559864d2eb586ae0e86bba816793ba65d124a3da2fd3e8b9fb524653fc39c2b48f3409ccda5615527d24266715da0c1ae116458ddaa9fbf171f879ca6e7859127
RSA e: 0x10001
Modulus size: 2048 bits, 256 bytes
Identical results (TLS alert 10 of length 7), retrying with changed messageflow
Identical results (Timeout waiting for alert), no working oracle found
NOT VULNERABLE!
