### ISSUE TITLE
EMQ cannot start on windows server core 1803

### ISSUE THREAD

**Issue by jingsong-liu** [emqx/emqx#1600]
#### Environment

- OS: Microsoft Windows Server Standard
- Erlang/OTP: 8.3
- EMQ: windows10-v2.2.0

#### Description

*A description of the issue*
unfortunately, no log/ console out.
`.\bin\emqqtd console

`
nothing happened, check the tasklist or netstat, no task started.

**Comment by terry-xiaoyu** [comment]
What is the EMQ version you're using?

**Comment by shannonls** [comment]
More information I hope can help :
Normally I use Powershell, all the command I run before is in powershell because windows server core only support powershell.

But there is a tricky way to open CMD: using remote desktop login windows server 1803, it show a CMD.
So today I did another test:
Using command prompt to run emqttd install/start/stop/uninstall, it works as expected.


I think the problem is the script under bin\ folder is not compatible with powershell.

Also, using `bin\emqttd install` createdwindow service  emqttd2-x seems not work correctly . It cannot managed by Windows Service Management Tools or `Get/Start/Stop-Service`. 

I it will be greatly useful if EMQ server has lanuch and control script support powershell, maybe a dedicated ps1 script is necessary because almost all EMQ for windows product situations are actually run on windows server,  not windows 7 or windows 10.

**Comment by terry-xiaoyu** [comment]
Thanks for your effort investigating this issue. We'll check this.

**Comment by Gilbert-Wong** [comment]
Hi, @jingsong-liu . Latest emqx3.1-rc.1 release has fixed this problem.

**Comment by jingsong-liu** [comment]
Thanks, nice release, I will try.
