### ISSUE TITLE
is there any method to stop the messages with some specific topic prefix forward to other node?

### ISSUE THREAD

**Issue by hui6075** [emqx/emqx#1601]
#### Environment

- OS: RHEL6
- Erlang/OTP: R19
- EMQ: 2.3.0

#### Description

we have 2 nodes, since share subscription is not supported, so is there any method to stop the messages which has the topic with prefix such as "/xxx/yyy" been forward to other nodes? because we don't want to receive a duplicate message under the share subscription with more then one node.

**Comment by terry-xiaoyu** [comment]
@hui6075 

Unfortunately it is hard to do that...

It was a design fault in the EMQ's router, which messages are dispatched to all of the nodes before retrieving the subscribers of the topic. Due to this, it is very hard to stop messages for shared topics been handled multiple times, and thus it's hard to implement shared subscription across nodes.

This issue is not easy to fix, because the router mixed the implementation of *shared subscriptions* with the normal ones. We need to refactor the code in EMQ 3.0.

If what you want to do is collecting data from EMQ and handling data in your backends, you should  [write your plugins](http://emqttd-docs.readthedocs.io/en/latest/plugins.html#create-a-plugin-project), and handle the `message.publish` event. That's because encoding and sending the MQTT messages would be an extra overhead you may want to avoid.

**Comment by HJianBo** [comment]
Hi @hui6075 You can use Local Shared Subscription to handle this. see #752

**Comment by hui6075** [comment]
@terry-xiaoyu 
thanks for your comments!
@HJianBo 
We use several client theads to make a share subscription for consumer load balance.
The share subscription topic filter is a concrete value, so I have hard code it in emqttd_pubsub.erl, refactor add_subscriber/3 and del_subscriber/3, for the share subscription, only call add_local_subscriber/3 and del_local_subscriber. seems it can work.

=============emqttd_pubsub.erl==============
add_subscriber(Topic, Subscriber, Options) ->
    Share = proplists:get_value(share, Options),
    Topic1 = binary_to_list(Topic),
    case string:str(Topic1,"/xxx/") of
        0 ->
            case ?is_local(Options) of
                false -> add_global_subscriber(Share, Topic, Subscriber);
                true  -> add_local_subscriber(Share, Topic, Subscriber)
            end;
        _ ->
            add_local_subscriber(Share, Topic, Subscriber)
    end.
=============emqttd_pubsub.erl==============
