### ISSUE TITLE
[help]why always show "node_down", I can not join a cluster

### ISSUE THREAD

**Issue by phper-chen** [emqx/emqx#1787]
#### Environment

- OS: ubuntu 16
- Erlang/OTP: 
- EMQ: emqttd-docker-v2.3.11

#### Description
Two separated EMQ servers in docker, A is 'emqttd@172.27.0.2', B is 'emqttd@172.18.0.2', after i used command "docker swarm" to join them, I got into B container in bash environment to exec "./bin/emqttd_ctl cluster join emqttd@172.18.0.2".

*A description of the issue*
the firewall is closed, and i have used docker-compose.yaml to set ENV, for example, EMQ_NODE_NAME=emqttd@172.18.0.2

**Comment by Gilbert-Wong** [comment]
Please give us more details

**Comment by spring2maz** [comment]
Hi @phper-chen 
What do you mean by 'firewall is closed'?
if it is closed, the nodes will not be able to connect each other.
Please note that firewall needs to be open between two nodes for pretty much ALL ports.
(Otherwise it must be open for EPMD 4369, and a manually set fixed port range for Erlang distribution listener).
Another typical reason is Erlang cookie being different between A and B.
`EMQ_NODE_COOKIE` is the variable to set from environment.

**Comment by phper-chen** [comment]
Thank u, i have solved it already. There was a misunderstanding in docker swarm.
