### ISSUE TITLE
TLS server: In state certify at ssl_handshake.erl:1626 generated SERVER ALERT: Fatal - Unknown CA

### ISSUE THREAD

**Issue by redmond007** [emqx/emqx#1830]
#### Environment

- OS: Docker/Alpine Linux
- Erlang/OTP: 20
- EMQ: v2.3.11

#### Description

I am trying to configure EMQ to use mutual TLS authentication between client and broker.  I've followed instructions here using self signed certificates and it worked.  https://medium.com/@emqtt/securing-emq-connections-with-ssl-432672ab9f06

I am now trying to configure my broker to use broker cert, key and CA certs from my company.  I am also configuring my client (MQTTFX) to use client cert, key and CA certs from my company.  It is not working with these certs.  I have used openssl verify to verify that these certs and keys are valid.

I'm seeing this error on the broker http://prntscr.com/kvvtk8
I'm seeing this error on the client http://prntscr.com/kvvt6x

One difference between my companys certs, keys and ca - and the self signed certs, keys and ca i used previously - is that my company's certs are multilevel - with a Root CA and an Intermediate CA.  I've pointed my emq config to a chain.crt file that contains both Root and Intermediate CA certs.

Does emq support multilevel CA certs?  

The error I'm seeing on the client is
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca

Does that mean that the client does not recognize the broker's ca - or the broker does not recognize the client's ca?  I'm not sure why I'm receiving this error because I configured the same CA on both the client and the broker.

Thanks for any advice on this.  I can provide further info if necessary.

**Comment by redmond007** [comment]
[configs logs.zip](https://github.com/emqx/emqx/files/2393731/configs.logs.zip)
Fyi I've uploaded a zip file with my emq.config, my emq log in debug mode, and a ss of my client config for reference.

**Comment by jerry-chao** [comment]
I have encounter the same problem. The CA maybe is not include the Root CA which is signed by itself.  My Company is signed by WoTrus CA Limited and WoTrus CA Limited is signed by Unizeto Technologies S.A. and Unizeto Technologies S.A. is signed by Unizeto Sp. z o.o. .Unizeto Sp. z o.o. is the root CA and Other CA are intermediate CA. Maybe your client cannot find Unizeto Sp. z o.o.  CA.  You can download it [here](https://www.censys.io/certificates/d8e0febc1db2e38d00940f37d27d41344d993e734b99d5656d9778d4d8143624/pem) and add it to your client CA chain if you use the the root CA.

**Comment by redmond007** [comment]
I've tried a ca chain with both the intermediary and root ca cert in one cert - the chain is installed on the operating system for both emq and the client.

I've noticed that s_client apparently works with this set up - but my client (MQTTFX) does not work.

**Comment by jerry-chao** [comment]
I am sorry i cannot give my company's CA but you can make one by yourself. I have written it down [here](http://leanote.com/blog/post/5ba34521ab6441313900345a) which i have test it myself.

**Comment by sudhamab** [comment]
hi Team, @Gilbert-Wong  , @terry-xiaoyu 

I am getting the same issue for the following environment

#### Environment

- OS: Ubuntu 18.04 bionic
- Erlang/OTP: 20
- EMQ: 3.1.2

#### ERROR MESSAGE 

2019-07-16 09:04:05.274 [notice] TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown
2019-07-16 09:04:05.274 [error] crasher:
    initial call: emqx_connection:init/1
    pid: <0.2802.0>
    registered_name: []
    exception error: no match of right hand side value {error,tls_alert}
      in function  emqx_connection:init/1 (src/emqx_connection.erl, line 146)
    ancestors: [<0.1714.0>,<0.1713.0>,esockd_sup,<0.1364.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1714.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 5751
  neighbours:
2019-07-16 09:04:05.276 [warning] [Alarm Handler] {supervisor_report,
                    [{supervisor,'esockd_connection_sup - <0.1714.0>'},
                     {errorContext,connection_crashed},
                     {reason,
                         {{badmatch,{error,tls_alert}},
                          [{emqx_connection,init,1,
                               [{file,"src/emqx_connection.erl"},{line,146}]},
                           {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}}]} set
2019-07-16 09:04:05.276 [error] supervisor: 'esockd_connection_sup - <0.1714.0>'
    errorContext: connection_crashed

#### DESCRIPTION

We are trying to connect from an Android app on the url path **ssl://abc.xyz.com:8883**
We are NOT using client side Certificates

I followed the instruction [here](https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6) but i still get the same error 

Although i did not use the "certonly" and "standalone" params as per above because I am also running a rest api server on the same machine

The certificates were generated by letsenscrypt and I copied them over to /etc/emqx/certs
as also described in [this issue](https://github.com/emqx/emqx/issues/2335)


I also verified that the letsencrypt certs were fine with the following command 

```
sudo openssl verify -CAfile /etc/letsencrypt/live/abc.xyz.com/chain.pem /etc/letsencrypt/live/abc.xyz.com/cert.pem
/etc/letsencrypt/live/abc.xyz.com/cert.pem: OK
```

Can you please advise us at the earliest? 

We would like to enable this asap and this is the last step we are left with .

thank so much in advance!

**Comment by 5HT** [comment]
I have the same problem:

> TLS server: In state certify at ssl_handshake.erl:1668 generated SERVER ALERT: Fatal - Handshake Failure - {bad_cert,invalid_key_usage}

It appears only when `{verify,verify_peer}` is settled in EMQ X.
