### ISSUE TITLE
REST API get topic's sessions/clients info

### ISSUE THREAD

**Issue by roytan883** [emqx/emqx#1886]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3.11

#### Description

*Can EMQ expose REST HTTP API query topic's sessions/clients info?*

Like: `GET api/v2/nodes/{node_name}/topic_sessions/{topicName}` or `GET api/v2/nodes/{node_name}/topic_clients/{topicName}`

As iOS clients almost offline, so when push msg to topic, need check all sessions/clients, find those iOS clientID and send msg to APNS simultaneously

**Comment by Gilbert-Wong** [comment]
We'll discuss it and determine implement this feature or not later.

**Comment by Gilbert-Wong** [comment]
Sorry, @roytan883. We have no schedule to implement this feature and expose the corresponding rest API because it would cost lots of computing resources and emqx cannot do it as well as professional databases. However, in emqx 3.2, there is a killer feature named rule engine. You can create a rule to monitor all subscribe events and unsubscribe events and then import subscribe topics and corresponding client/session info into your web server or databases. After data is imported into your database, you can use SQL or other query tools to get the information you want.
