### ISSUE TITLE
emqtt 2.2 erl_crash_dump

### ISSUE THREAD

**Issue by cjmNo1** [emqx/emqx#2029]
#### Environment

- OS: centOs
- Erlang/OTP: 
- EMQ: emqttd 2.2

Problem : erl_crash_dump

 Description
we are using emqtt version 2.2 on centOs and after running for a period of time

Log 1:
=erl_crash_dump:0.3
Wed Dec  5 01:33:25 2018
Slogan: eheap_alloc: Cannot allocate 3280272216 bytes of memory (of type "heap").
System version: Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:4:4] [async-threads:32] [hipe] [kernel-poll:true]
Compiled: Tue Mar 14 13:51:29 2017
Taints: dyntrace,crypto,bcrypt_nif,asn1rt_nif,erl_tracer
Atoms: 34252
Calling Thread: scheduler:3

[crash.txt](https://github.com/emqx/emqx/files/2647338/crash.txt)

Thanks for all help!

**Comment by terry-xiaoyu** [comment]
Hi, @cjmNo1 

May I know more about your pub/sub scenario?

If you are consuming messages from a single subscriber, you could use [shared subscription](https://developer.emqx.io/docs/emq/v3/en/advanced.html). 

If you are publishing lots of messages with different topic, you may need to change the `acl_cache` to false in emq.conf.

BR,
//Shawn

**Comment by terry-xiaoyu** [comment]
Set up a test environment and try your scenario that is similar to your production environment. Then I would help you investigate the problem if you could give me the permission accessing your test servers.

I guess it might be caused by the `single subscription` or `acl_cache` mentioned in my last response. 

BTW, we only support English issues on githhub.
