### ISSUE TITLE
 fail to use topic trace

### ISSUE THREAD

**Issue by xiou1990** [emqx/emqx#2035]
#### Environment

- OS: centos6.5
- Erlang/OTP: 
- EMQ: emq V2.3.11

#### Description
what should i do to trace topic

[root@instance-uas0uz87 emqttd]#emqttd_ctl trace topic "FND" "FND_TOPIC.log"
trace topic FND successfully.
[root@instance-uas0uz87 emqttd]# cat error.log

2018-12-07 18:19:27.858 [error] <0.1161.0>@lager_file_backend:119 Failed to open log file FND_TOPIC.log with error permission denied
*A description of the issue*

**Comment by terry-xiaoyu** [comment]
@xiou1990 Hi, you could change the permission of that file(or dir) and add the tracer again. This is because lager doesn't verified the access permission before adding a new log handler. But I don't want to fix it on emqx 2.x.

I've verified it on emqx 3.0.1 and it works well, the CLI fails with an `eacces` error in case of access failure. Thanks for your feedback. :-)
