### ISSUE TITLE
Shared subscription with clean-session = false and persistence

### ISSUE THREAD

**Issue by perroudchris** [emqx/emqx#2143]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: emqx 3.0.0

#### Description

Hello. I'm trying to have this scenario: 

1.A/B/C/D connected with **clean-session=false**
2. A/B/C/D all **shared-subscribe** a same topic
3. A/B/C/D get disconnected for some reason
4. 12 messages pub clients are coming on the broker
5. A (alone) connects once again with clean-session= false

If the parameter **broker.shared_dispatch_ack_enabled = true**  is enabled, there's no persistence (retainre) and I cannot see the 12 messages that came when A/B/C/D were disconnected. 

If I use a "non-shared" topic, retainer works. 

So my question : it is possible to make a share subscription only on online clients but with retain system if no "sub-client" is there ?

**Comment by spring2maz** [comment]
Yeah, found this nice comment in code:
```
                    %% failed to dispatch to this sub, try next.
                    %% 'Reason' is discarded so far, meaning for QoS1/2 messages
                    %% if all subscribers are offline, the dispatch would fail
                    %% even if there are sessions not expired yet.
                    %% If required, we can make use of the 'no_connection' reason to perform
                    %% retry without requiring acks, so the messages can be delivered
                    %% to sessions of offline clients
```
Will work on a fix.

**Comment by perroudchris** [comment]
Thanks a lot @spring2maz .

**Comment by nicklasfrahm** [comment]
Could this be reopened, because I am facing the same challenge as described above. I performed some testing and read the code that was submitted as part of the PR.

Current behaviour: If no client is connected, the message will be dispatched to a random client session of that shared subscription. This however requires that any of the previously connected clients will ever come back.

Expected behaviour: The message should be retained without binding it to a certain client ID and session. Once a client without a clean session comes online, the retained messages will be dispatched to this client.

This is at least how I am understanding it. Especially if it is supposed to be a queue.

**Comment by zmstone** [comment]
HI @nicklasfrahm Thank you for the feedback.
currently messages are only stored to subscriber's sessions.

we have a work-in-progress project to add on-publish message persistence,
which will then allow shared subscribers to poll a backlog to consume.

You are welcome to create a new issue so we can keep track of this requirement.
Thank you

**Comment by nosovk** [comment]
@zmstone is it any updates regarding it? Was it implemented?
