### ISSUE TITLE
Ability to cache ACL during auth, and not during pub/sub

### ISSUE THREAD

**Issue by sriutmobile** [emqx/emqx#2254]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: EMQX-Broker

#### Description

Looking for provision to fetch ACL during auth and cache them once the client is authenticated. This way, EMQX can validate the topics during pub/sub from the ACL cache instead of looking up through http, mongo, mysql, etc for ACL validation.

The http(s) API specified at auth.http.auth_req could return the ACL and EMQX can cache them.

**Comment by terry-xiaoyu** [comment]
@sriuppu 

ACL caching is enable by default, assume you are using emqx 3.0, the related configurations are (in emqx.conf):

```
## Whether to enable ACL cache.
##
## If enabled, ACLs roles for each client will be cached in the memory
##
## Value: on | off
enable_acl_cache = on

## The maximum count of ACL entries can be cached for a client.
##
## Value: Integer greater than 0
## Default: 32
acl_cache_max_size = 32

## The time after which an ACL cache entry will be deleted
##
## Value: Duration
## Default: 1 minute
acl_cache_ttl = 1m

## The action when acl check reject current operation
##
## Value: ignore | disconnect
## Default: ignore
acl_deny_action = ignore

```

ACL access result is cached per connection, this means that it is cleaned after the client is disconnected.

ACL cache is stored in the form of {PubOrSub, Topic} => {AllowOrDeny, Timestamp}. For details see https://github.com/emqx/emqx/pull/1744

The `acl_cache_ttl` is the time after which the cache entry will be deleted, if no subsequently access to that cache entry during this time. Change it to a larger value as you wish.

**Comment by sriuppu** [comment]
I understand that currently there is a feature which can be enabled to cache ACL for a topic whenever the client publishes/subscribes on that topic for the first time or if the TTL has expired.

But what I am looking for is to store all the allowed topics for pub/sub for that client (complete ACL set) in cache at once on successful client authentication, instead of caching each topic when client does a publish/subscribe.

**Comment by terry-xiaoyu** [comment]
@sriuppu EMQ is not support this kind of ACL caching, and we currently have no plan to change the caching mechanism to this.

**Comment by zhengyupan** [comment]
Hi @sriuppu We will take this to feature requirement discuss and let you know what comes out.

**Comment by mononym** [comment]
@sriuppu, there are a couple of different things here to address and I'll try to cover them as much as possible.

- Getting ACL permissions during connection rather than when trying to actually publish/subscribe.
We don't currently have any plans to change this behavior. The vast majority of clients publish/subscribe to things almost as soon as they are connected and this would just add extra latency to the connection process.

- Loading ALL ACL rules for a client using config/Mnesia
If you use the local config file or Mnesia that will get the same effective result you are looking for. All the data being present and effectively cached or at least without needing to spend time on an external roundtrip to a database or webserver.

The config file would be good for a small number of rules that don't change while Mnesia would be better for larger sets of data including those that do change. Currently there is an API for the Mnesia ACL to populate the database with the rules you have so you can push any changes to the cluster. Coming up in v5.0, though, there will be an enhanced ability to sync databases and so it might become easier to sync ACL data to the cluster from an external system.

-Loading ALL ACL rules for a client with HTTP or a database call
You do have the ability to control the actual sql request from the config, meaning you could theoretically write a query to return all the data for a specific client, but only the actual result that was asked for would be cached. So if there are 20 rules that apply to a client and they publish to a single topic, the result of the logic would be that no matter what the query was only that ACL data for that single topic will be cached for that client.

This last one is an area in which we could possibly improve, though it would take a little thinking about and establishing an expected 'shape' of the data to be returned from HTTP/Database calls so that keys can be mapped and grabbed properly. However given the flexibility of the other ways of getting that ACL data and the upcoming changes with v5.0 I can't say where this type of change will fall in our priorities if it is a desired one.

**Comment by mononym** [comment]
Closing this in favor of a specific feature request for handling multiple results from an ACL query.

See #6444
