### ISSUE TITLE
How to send image, audio or video?

### ISSUE THREAD

**Issue by Joey-Lee** [emqx/emqx#2432]
Are there any code examples of send image, audio or video?
Thanks a lot.

**Comment by zhengyupan** [comment]
Hi @Joey-Lee , 
you can carry any files in the payload of MQTT message, with encoding you want.
Here is a nice article about sending files over MQTT with python code example for Steve, the code sends files in multiple blocks and let you handle files at any size. This article is very informative. Steve has authorized free use of this code for any purpose. Thank you, Steve!
http://www.steves-internet-guide.com/send-file-mqtt/ 

python is very friendly to read, you can port it to any programming language you are familiar with.

I am closing this issue here.
