### ISSUE TITLE
Shared Subscription

### ISSUE THREAD

**Issue by sshhawwnn** [emqx/emqx#2446]
#### Environment

- OS: CentOS 7.6
- Erlang/OTP: 
- EMQ: v3.1-rc.1

#### Description

*A description of the issue*
I am trying to understand more about the shared subscription.

I have a publisher and 3 subscriber connected to the broker with the subscriber all subscribed to a shared subscription topic. I had one subscriber purposely disconnected from the broker. The disconnected subscriber still receives messages from the publisher even if the subscriber is disconnected. Is this correct? Shouldn't the message goes only to the "online" subscriber unless all 3 subscriber is offline?

**Comment by turtleDeng** [comment]
@sshhawwnn Thank you very much, we will fix it as soon as possible and release it in 3.1-rc.3.

**Comment by spring2maz** [comment]
The subscriber is considered 'offline' by the broker only when its session is expired.
Could it be that the session was still around when the subscriber client is disconnected ?
e.g. clean clean session flag was not set to true ?

**Comment by Gilbert-Wong** [comment]
From your issue, you said that subscriber would receive message even it is disconnected. How could this be ? Could you please give me more details?

**Comment by sshhawwnn** [comment]
All the subscriber clean_session is set to false in order to have offline message persistence. However, when one subscriber goes offline, the subscriber still receives offline messages. Is this a normal behavior or should the message goes only to the other two "online" subscriber unless all 3 subscriber is offline?

**Comment by phanimahesh** [comment]
No. The behaviour you see is intended. The broker does not know if the connection was interrupted briefly and will reconnect immediately, or if it went offline for good. The broker expects the client to reconnect before session expires, and faithfully queues the messages until then. Default session expiry interval is long, it is a good default for most use cases.

For shared subscriptions processing a queue of tasks, however, shorter session expiry in the order of few seconds would be useful.

You can configure sessions to expire soon if you want the shared subscriptions to ignore offline clients sooner. Clean_session wont have an effect since it is applied at the beginning of the session, and won't affect session expiry.

We will discuss and consider ways for a client to notify broker that it is going away for good, and to ignore it for shared subscriptions.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue, if there are any problems, you can reopen.
