### ISSUE TITLE
EMQ on AWS : which edition?

### ISSUE THREAD

**Issue by alflexRH** [emqx/emqx#2527]
i saw tweet https://twitter.com/emqtt/status/1108915134074773504 and got a small instance with EMQX to play around with.

but i have 2 questions:
1) is there a list somewhere with tests or estimates of how many tcp/tls connections a certain instance type can handle?

2) is this the EMQX Enterprise version? It looks like this from the description of the AWS image ,but i cannot find where to configure the kafka/rabbitMQ plugins.

**Comment by jinfahua** [comment]
The capability of a certain instance is up to several factors, please refer to this link: https://developer.emqx.io/docs/tutorial/en/faq/faq.html#q-how-to-estimate-resource-usage-of-emq-x. You can post your requirement here, and we could give you some advice.

The version deployed at AWS is 3.0.1 open source version, not enterprise version. We're now planning to provide EMQ enterprise deploying at AWS in 2Q - 3Q, 2019. If you're not urgent, you could wait for our official release.

**Comment by alflexRH** [comment]
That link tells me that i need more resources if i have more connections, use TLS or more messages. that is the obvious part. The calculator tool is still TODO.


The AWS image description is extremely misleading in that case:

[ Product Overview
EMQ X Broker is an open sourced MQTT message broker, which implements both MQTT V3.1 and V3.1.1 protocol specifications and supports MQTT-SN, CoAP, WebSocket, STOMP and SockJS as well. It is a distributed, massively scalable, highly extensible broker which a single node alone can support millions concurrent connections and much higher when clustering. It has been deployed by 5000+ WW users and served 50 million IoT and Mobile connections.

EMQ X Enterprise is the enterprise version of the EMQ X Broker which extends the functions and enhance the performance. It improves the system architecture of EMQ X Broker and adopts scalable RPC mechanism which provides more reliable clustering and higher performance of message routing.

EMQ X Enterprise supports persisting MQTT messages to Redis, MySQL, PostgreSQL, MongoDB, Cassandra and other databases. It also supports bridging and forwarding MQTT messages to enterprise messaging middleware like Kafka and RabbitMQ. 

EMQ X Enterprise can be used as a highly scalable, highly reliable, highly available enterprise graded connectivity platform for IoT, M2M, smart hardware, smart home and mobile messaging applications that serve millions of devices/terminals.]

**Comment by jinfahua** [comment]
Sorry for misleading you. The TODO will be updated when EMQ enterprise deploying at AWS is released at 2Q - 3Q, 2019.

**Comment by mchsk** [comment]
@jinfahua Hey! I have been looking for the docs for EMQ Enterprise AWS solution, could you guide me? Thank you so much

**Comment by dishantghai** [comment]
Hi, is EMQX Enterprise available on AWS ?.. how can i estimate pricing ?

**Comment by zhanghongtong** [comment]
Hi, @dishantghai 
You can try our [EMQ X Cloud](https://cloud.emqx.io/)

**Comment by mononym** [comment]
This thread seems to have a couple different questions within it, and many things have changed since it was first asked.

There is [EMQ X Cloud](https://cloud.emqx.io/) for those looking for a hosted enterprise solution with pricing available on the website alongside [documentation](https://docs.emqx.io/en/cloud/latest/) describing the product.

For self hosting it is not quite so clear cut as to be able to offer a specific pricing estimate, especially one that would be good long term as we continually try to improve the product and performance and prices change outside of our control. What I can give you, even though it isn't much, is this page where we show some [test results](https://www.emqx.com/en/resources?type=reports) for connections and describe the performance during said tests.
