### ISSUE TITLE
How to ensure emqx-web-hook callback sequential?

### ISSUE THREAD

**Issue by PMExtra** [emqx/emqx#2604]
#### Environment

Official emqx/emqx docker container with tag v3.1.1

#### Description

The emqx-web-hook plugin will call my HTTP API when some events triggered. But when I receive many callbacks in a momnet, I'm not sure about the order in which they are triggered, because of some well-known reasons such as network dalay and so on.

In my case, I use web-hook to determine if the client is online. But I think the result will be not reliable if I can't ensure the callback sequential.

I think maybe you can add a sequence id or millisecond timestamp to the callback parameters to help us determine the order.

**Comment by HJianBo** [comment]
Hi, @PMExtra Don't worry about that. The client process of EMQ X call these web-hooks is sync. 

In other words, to one client events, the next HTTP request must wait for the previous request responded success (or failed)

**Comment by PMExtra** [comment]
All right, it seems very simple. But then I'm worried about another problem, what happens if I don't finish the callback so quickly? There is more and more hooks piled up, and then? Will it crash? Is there a threshold of max queue length of hooks?

**Comment by tradingtrace** [comment]
**I'm a newcomer to EMQX, just starting to read the code. Please correct me if I have any mistakes.**

It's a good question!

I think all webhooks are called synchronously for now, and there is no threshold.

My first thought is: Yes, it's a good idea to spawn a process or start a gen_server to do `hooks` things asynchronously.

But after reading code, I think it's not exactly correct because:

1. Some logic relies on the return of `hooks`(Webhook is also an `Emqx hook`, but I found all webhooks only return `ok`).
2. Most `hooks` are run in _**user connection processes**_ (e.g. `emqx_hooks:run/2` and `emqx_hooks:run_fodl/2` called in some modules like `emqx_connection.erl`, `emqx_protocol`, and `emqx_session.erl`). It will only affect a particular user not other users and Emqx services if a hook finishes slowly. And also if we have 10K clients subscribing to the same topic, it's crazy to spawn other 10K processes or send 10K messages to several processes in a short time to iterator `message.acked hooks`.

So I think, it's better to synchronously run **all hooks** which called in user connection processes, but asynchronously run the **webhooks** which called in some shared processes (e.g. `'message.publish'` and `'message.dropped'` in emqx_broker.erl and emqx_sm.erl).

**Comment by HJianBo** [comment]
Hi @PMExtra sorry for late reply. The @tradingtrace explanation is very explicitly:

> I think all webhooks are called synchronously for now, and there is no threshold.
> It will only affect a particular user not other users and Emqx services if a hook finishes slowly.

But all of the hooks is running at **client connection/session process**, included the `message.publish` and `message.dropped`. SO:

In addition, the http request of `webhook` is synchronously too. So, the client connection/session process will be slow down by http request.

With the  more and more http request piled up, the memory consumed by EMQX will continue to increase until the system crashes.

When the scenario occurs, we should to improve the http handling speed of emqx_web_hook or the backend web services.

**Comment by PMExtra** [comment]
@HJianBo Thanks a lot.
