### ISSUE TITLE
Connected/Disconnected Status

### ISSUE THREAD

**Issue by satrox28** [emqx/emqx#2606]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 19.2
- EMQ: 2.2

#### Description

We have around 100,000 clients connected all time and would like to display there real time status on our website.

To achieve that we would like to capture the connected/disconnected events and persist to our database RDBMS.

Which is a better way to do?

1) Creating a emqttd plugin and during the client connection phase capture the events and call our endpoint API internally to pass the message and our API will persist the data to our database.

2) On the webhook specify our API and store the message from there to DB. I feel this will put load on the emqttd broker once all clients turn connected/disconnected.

**Comment by HJianBo** [comment]
Undoubtedly, the first option is the best way!  However, it requires that you must use Erlang to develop your plugins. In this plugin, you can use better design and more effective interface to handle the amount of client connected/disconnected events.

About seconds option, It is a friendly way to implement this. As you said, it will really enlarge the load of emqttd broker once all clients connected/disconnected. Because the [http client](http://erlang.org/doc/man/httpc.html) implemented of web_hook is not efficiency method.

**Comment by HJianBo** [comment]
Close first.

Please reopen it if you have any questions
