### ISSUE TITLE
Questions about ACL cache

### ISSUE THREAD

**Issue by dremfly** [emqx/emqx#2727]
#### Environment

- OS:centos7 
- Erlang/OTP: 
- EMQ: 3.2

#### Description

启用了mysql认证插件
1，当数据库和acl.conf配置文件同时有鉴权规则时，检测顺序是什么？
2，数据库中的规则是按着id来顺序检查的吗？
3，有一个需求，一台设备配一个topic，账号和密码，这台设备只能用这个账号密码登录，当设备量很多时，acl匹配检查岂不是要花费好长时间，在开启acl缓存时，内存会吃掉很多吗？

以上问题，查询文档无果，寝食难安，遂来求助，谢谢！

**Comment by terry-xiaoyu** [comment]
1. About the authentication/acl chain: https://developer.emqx.io/docs/broker/v3/en/guide.html#access-control-list,
and the acl.conf is at the end of the chain.

2. Yes, the ACL matching is done by the order of the rules stored in the db.

3. The ACL cache entry is stored in the separated memory of each client, in the form of `{PubSub, Topic} -> Result`, see https://github.com/emqx/emqx/pull/1744

e.g.

{publish, 't/a'} -> allow 
{subscribe, 't/b'} -> deny

And the ACL will be cleaned after a configurable interval, which defaults to 1min.

So if there's a client sends messages to all other clients, it may consume lots of memory for caching the ACLs, but will be cleaned in 1min. For this scenario, use the [pub/sub API](https://developer.emqx.io/docs/broker/v3/en/rest.html#publish-subscribe) instead of mqtt client, as no ACL validation is done for the pub/sub API.

**Comment by terry-xiaoyu** [comment]
@dremfly Please re-write your questions in English, thanks

**Comment by dremfly** [comment]
非常感谢，but my english is not good(｡•́︿•̀｡)
