### ISSUE TITLE
[Feature request] Auto gzip/unzip text message

### ISSUE THREAD

**Issue by yixingjia** [emqx/emqx#3099]
It will be great that EMQX can automatically gzip and unzip text based message base on some threshold. 

Eg, if the message payload is very small, say <50 byte then there is no need for the compression. 

if the message payload is kind of large like > 10 kb. Compression will save a lot of network bandwidth. 

Ideally there should be a configuration item in the emqx.conf file that support custom definition about auto compress threshold.

**Comment by tigercl** [comment]
Thank you for your feedback. We will consider implementing this function.

**Comment by zmstone** [comment]
message payload (compress or not) is at application level, EMQX as a broker can not interfere unless the MQTT specification supports it, otherwise there will be inter-operational issue.
e.g. a publisher sends a message, EMQX compress it, a subscriber receives it, but no clue if it's compressed or not.
