### ISSUE TITLE
Clients can't receive messages from broker after reconnect

### ISSUE THREAD

**Issue by q821863269** [emqx/emqx#3176]
#### Environment

- 我使用的EMQ版本是v3.4.5
- 软件包为Docker/amd64/zip
- 使用Docker的形式安装运行的

#### Description

遇到的问题是：
我创建了两个客户端连接Broker（这两个客户端作为消息接收者）
Topic使用的是共享订阅：$share/simulator/up/simulator/300024/#
MqttConnectOptions：设置setCleanSession(false);
QOS设置为：0

然后我再创建一个客户端连接Broker（该客户端作为消息发送者）
Topic使用的是：up/simulator/300024/
MqttConnectOptions：设置setCleanSession(true);
QOS设置为：0

当3个客户端都在线的时候，消息发送接收都正常。。。

将两个客户端都下线，因为setCleanSession(false);
所以Seesion通道会被保留
此时客户端发送消息，通过RestApi进行查询结果如下：
![image](https://user-images.githubusercontent.com/37721392/72231728-062d1200-35f8-11ea-96b3-d43886c37726.png)
发现mqueue_len中有缓存了消息。

此时在将两个客户端重新上线
![image](https://user-images.githubusercontent.com/37721392/72231889-cf0b3080-35f8-11ea-9625-0abec04f3a1e.png)
通过RestApi查询，消息确实减少了32条（这里为什么只会减少32条，如何才能把所有缓存消息都进行下发？？？）
![image](https://user-images.githubusercontent.com/37721392/72231771-41c7dc00-35f8-11ea-8d95-e7a5fa02d85e.png)
![image](https://user-images.githubusercontent.com/37721392/72231774-47252680-35f8-11ea-8694-0c4d583f505f.png)
在Log中有追踪到消息从Broker下发了

但是我的客户端，没有接收到Broker发来的消息
![image](https://user-images.githubusercontent.com/37721392/72231924-08dc3700-35f9-11ea-9aa5-ca22febd4ef2.png)
![image](https://user-images.githubusercontent.com/37721392/72231927-0d085480-35f9-11ea-9db7-dc2f2b9e6e31.png)

希望EMQX的技术大佬们帮忙解答一下。。。

**Comment by xyz361** [comment]
Environment

- The EMQ version I use is v3.4.5
- The package is Docker / amd64 / zip
- Install and run using Docker

Description
The problems :
I created two clients to connect to EMQ broker (these two clients act as message receivers)
Topic uses a shared subscription: $ share / simulator / up / simulator / 300024 / #
MqttConnectOptions: Set CleanSession=false;
QOS is 0 .

Then I create a client to connect to the broker (the client acts as message sender)
Topic : up / simulator / 300024 /
MqttConnectOptions: Set CleanSession=true;
QOS is 0 .

When all three clients are online, sending and receiving messages are normal. . .

Take both clients offline because setCleanSession = false ;
So the Seesion channel will be kept ;
At this time, the client sends a message, and the query result through RestAPI is as follows :
![image](https://user-images.githubusercontent.com/37579443/72233650-8f961180-3603-11ea-85d6-9a267a577673.png)

It is found that messages are cached in mqueue_len .

At this point, the two clients are back online :
![image](https://user-images.githubusercontent.com/37579443/72233689-c79d5480-3603-11ea-9727-5d287ab86b86.png)
Through the RestAPI query, the number of messages is indeed reduced by 32 (so why there are only 32 reductions here, how can I send the cached messages ???)

![image](https://user-images.githubusercontent.com/37579443/72233718-fadfe380-3603-11ea-9787-a6ae1f202954.png)
![image](https://user-images.githubusercontent.com/37579443/72233720-0206f180-3604-11ea-8f5b-c1ee804154a4.png)

I can see that there are some messages in the Log sent from the Broker .

But my client did not receive these messages from Broker .
![image](https://user-images.githubusercontent.com/37579443/72233776-485c5080-3604-11ea-9a30-3601a7b941e9.png)
![image](https://user-images.githubusercontent.com/37579443/72233781-4db99b00-3604-11ea-931c-92fed698e72b.png)

I hope EMQX's technical bulls can help answer it . TKS .

**Comment by tigercl** [comment]
@q821863269 In this case, we recommend capturing the network packets to confirm whether the message is sent to the client first.

**Comment by q821863269** [comment]
> @q821863269 In this case, we recommend capturing the network packets to confirm whether the message is sent to the client first.

我抓包发现，Broker有将消息发送到客户端，后面我检查了代码，发现是我代码上有些问题。

修改代码后，重连接收到了Broker发来的消息，但是Broker只发送了缓存消息中的32条，消息缓存队列中还有消息，但是一直不会发送到客户端，客户端每重连一次，就发送32条，这个问题，我应该如何处理呢？？？

**Comment by HJianBo** [comment]
Hi, @q821863269 This bug has fixed at v4.0. Maybe you can try it

**Comment by q821863269** [comment]
@HJianBo Ok, I'll try. Thanks for your help

**Comment by HJianBo** [comment]
Hi guys, After a checking, I confirm the v4.0 has fixed it
