### ISSUE TITLE
connections limit of 100000

### ISSUE THREAD

**Issue by xianghao1986** [emqx/emqx#3387]
The official website says that the open source version can only support 100,000 connections, but in my tests, I was able to reach a million connections on a single machine, how to explain

**Comment by HJianBo** [comment]
Hi @xianghao1986 The standards of the opensource edition are millions of connections.

Where do you see 100,000 connections? Can you share the link? Thanks

**Comment by aevteev** [comment]
Hello @HJianBo, the official documentation says:
EMQ X Broker: EMQ X open source version, supports the popular IoT protocols, such as MQTT, CoAP and LwM2M. **It supports 100k level concurrent MQTT connections**.

EMQ X Enterprise: EMQ X enterprise version. It is based on the open source version, and adds data persistence (support Redis, MySQL, MongoDB or PostgreSQL), data bridge to Kafka, LoRaWAN support, EMQ X monitoring, Kubernetes deployment etc. **It supports 1M level concurrent MQTT connections**.

https://docs.emqx.io/broker/latest/en/faq/faq.html

**Comment by igolubic** [comment]
Hi, it would be great if somebody can explain this. Is there a real (like software) limitation, license limitation or?

**Comment by mr-bremm** [comment]
Hello, 
I've just stumbled upon the same issue (showing 100k connections for Broker X) and just send a lengthy email to sales for clarification on this matter, as well as any other potential limits on available features (# of accounts, events/messages, topics etc)

Happy to share the results here once received.

**Comment by zmstone** [comment]
hi all

the information in faq is very much outdated, we will fix it soon.

It has been updated in sales page since long ago, https://www.emqx.io/products/pricing

I’m not quite familiar with the early versions, but my best guess is:
In the old time, open source and enterprise code was (almost) the same but default config divergence was significant.
The lack of stress test for open source led to lower limitation recommendations.

I am pretty sure that the defaults for 4.x open source can support the same level of scalability as enterprise please enjoy.
What’s more, since 4.3, we merged enterprise and open source not only to the same git tree, but also the same git branch.
In the long run, you can count on us disclosing more and more enterprise edition features to the community too

**Comment by mr-bremm** [comment]
Fantastic!Thank you very much. At this time, you're the best :)

**Comment by itweb62** [comment]
Hello,
So if i understand the community edition can handle 1 millions connection ? 
so if i have 2 node i can handle 2 millions ?
