### ISSUE TITLE
The exception "Dropped msg due to mqueue is full" don't  consistent with the actual situation 

### ISSUE THREAD

**Issue by qiufujian** [emqx/emqx#3551]
Environment：
      centos 7.6
      emqx broker 4.0
      cpu : 2 cores of x86_64;   RAM: 3GB

I run emqx broker 4.0 docker image on my centos server. I edit the emqx.conf and set the max_queue_len to 512 and store_qos0 = true. This means that the emqx broker would store the qos0 message if the message doesn't forward in time ?  I am not sure about this doubt.

Then I start two threads(running in java 8). One is mqtt-publish-thread, which publishes one piece of message per 200ms. And the other is mqtt-subscribe thread, which deals with one piece of message per 1000ms.  To get the exception above, I let publish-thread send 1000 messages in total.

Under this situation, I do see exception log in my server which shows like below:
![image](https://user-images.githubusercontent.com/22230082/85353501-f7e60900-b53a-11ea-97c8-73da91347396.png)

That is to say,  some messages are indeed dropped. But What makes me unexpected is that my-subscribe-thread receives 1000 messages finally,  and there is no any error in my subscribe-client.  Oh, how to explain this problem?

**Comment by tigercl** [comment]
@qiufujian `mqueue_store_qos0` indicates that QoS0 messages will be stored when the connection is disconnected.

**Comment by qiufujian** [comment]
@tigercl 
Is this meaning that the qos0 messages would not be stored if the connection is connected? 
But if the speed of  publish-process publishing message much faster  than the speed of the subcribe-process dealing with messsages, where will the message being not dealt in time  be stored in?

**Comment by tigercl** [comment]
@qiufujian If the client is connected, QoS 0 messages will be sent directly, and QoS 1 and QoS 2 messages will be stored in the message queue if the flight window limit is reached.

**Comment by qiufujian** [comment]
@tigercl 
You mean that no matter how many qos0 messages arrive emqx broker, the broker would forward it to  corresponding client right away.  So if client can not deal with message fast enough,  will some messages be discarded by client?

**Comment by GopherJ** [comment]
@qiufujian are you using `paho.mqtt.golang`?

**Comment by qiufujian** [comment]
I used mosquitto as mqtt publish client in cpp, and eclipse. paho. mqttv3 as subscribe client in&nbsp; java.&nbsp;

---Original---

**Comment by xianghao1986** [comment]
> @tigercl
> You mean that no matter how many qos0 messages arrive emqx broker, the broker would forward it to corresponding client right away. So if client can not deal with message fast enough, will some messages be discarded by client?

How do you solve it finally?

**Comment by roysG** [comment]
Yes, this bug also happened to me, is there any solution, this killed my server until i made manually restarted

**Comment by oratchade** [comment]
Happy new year folks 🎉
+1 having the same issue, anyonye to help ?

**Comment by zmstone** [comment]
While I do not have the answer to why the message count were not as expected in the original post.
I feel like there is a need to a detailed explanation of the internal send-buffer for each EMQ X subscriber.

The send buffer consist of two parts:

`(rear)[mqueue][in-flight-window](head)`

Messages are pushed to (the rear of) `mqueue` under either of below conditions
1. in-flight-window is full
2. for persistent session subscriber, the client is not connected

Uncompleted QoS 1 and QoS 2 deliveries take up credits from `in-flight-window`
e.g. when the window size is 10, and there are 10 QoS 1 messages sent to the subscriber without ack received yet: the window is full.

For QoS 0 messages, the rule is simple:
* If the client is connected (socket open) the message is sent immediately regardless of the `in-flight-window` status
* If the client is not connected (socket closed) the message is pushed to `mqueue` when `store_qos0` is set to `true` (default is `true`).

NOTE: the 'send to the subscriber' from EMQ X's perspective means: put the bytes to tcp send buffer.
Since there is no push-back at MQTT level for QoS 0 messages, the push-back to EMQ X essentially depends on two things:
1. TCP flow control
2. The TCP buffer size

So to answer this question from @qiufujian 
> You mean that no matter how many qos0 messages arrive emqx broker, the broker would forward it to corresponding client right away. So if client can not deal with message fast enough, will some messages be discarded by client?

Yes, the broker might be able to send more messages than the clients can process (as a burst), however, as answered above, EMQ X will eventually slow down at some point when the TCP buffer is full.
