### ISSUE TITLE
Emqx client is offline after connecting for a period of time

### ISSUE THREAD

**Issue by blue-stu** [emqx/emqx#3586]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
After a period of time, the log has the message: "Dropped msg due to mqueue is full: Message(Id=ª$MfÃé>à
, QoS=2, Topic=client3/, From=<<"1594448048167">>, Flags=[], Headers=#{peerhost => {42,180,191,139},
  proto_ver => 4,protocol => mqtt,username => <<"admin">>})" ; then after 20 minutes, there has the messsgae: "[error] message=channel_closed driver=tcp socket="#Port<0.14342>" action=stopping", in the end, the clients are disconnected.

**Comment by HJianBo** [comment]
Hi @blue-stu Please follow the issue template to show your broker version and other key basic information.  It is convenient for us to analyze the problem phenomenons.

> [error] message=channel_closed driver=tcp socket="#Port<0.14342>" action=stopping"

The log is not produced by your client process. It is not a reason for there. Could you provide all of the broker logs located at `./log` directory

**Comment by blue-stu** [comment]
The broker version is 4.1.0, the log is get from emqx broker 4.1.0, the log file name is "emqx.log.1",the message is "2020-07-11 14:46:39.133 [error] message=channel_closed driver=tcp socket="#Port<0.14342>" action=stopping"

**Comment by HJianBo** [comment]
Could you post all of your emqx.log.* files here?

**Comment by blue-stu** [comment]
[emqx.log](https://github.com/emqx/emqx/files/4910218/emqx.log)

**Comment by HJianBo** [comment]
> 2020-07-11 14:46:39.133 [error] message=channel_closed driver=tcp socket="#Port<0.14342>" action=stopping

In addition to this, I don't have observed more logs for it. Are you sure the `1594447880662` client disconnected at this time: `2020-07-11 14:46:39.133`?

**Comment by blue-stu** [comment]
yes, I'm sure

**Comment by terry-xiaoyu** [comment]
@blue-stu The subscriber was probably killed due to a large message queue, but the logs not show this, might because of log msg drop.

To confirm this you could attach to the erlang shell and verify the message length using `etop`:

**Note: Do not Ctrl-C**
```
$ emqx attach

spawn(fun() -> etop:start([{output, text}, {interval, 5}, {lines, 20}, {sort, msg_q}]) end).
```

Type **Ctrl-D** to quit the erlang shell.

The above command will print the top 20 processes very 5 seconds, sorted by message queue length. If the msg len is too long it would harm the system. To kill the overloaded connection automatically you could configure `zone.external.force_shutdown_policy` in emqx.conf.

**Comment by GopherJ** [comment]
@blue-stu  are you using `paho.mqtt.golang` ? I had this issue if I use paho.mqtt.golang

**Comment by roysG** [comment]
Any solution for this bug?
