### ISSUE TITLE
Support the WebSocket cookie fields for Auth plugins

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#3747]
Hey I read @phanimahesh PR and from what I understood, the headers has been added into the ClientInfo therefore the cookies are in the ClientInfo as well. But where is it used concretely? How can I use it with the different auth plugins? 

If I read the emqx-auth-http docs, I can't see the headers, neither cookies as params. I went further and I tried to read the erlang code with my really basic understanding of it. I think it the params could be added here https://github.com/emqx/emqx-auth-http/blob/master/src/emqx_auth_http_cli.erl#L78 adding a line in the map to pass the sessionId (the name could be specified in the config). Or maybe forward the cookies?

I saw as well a feature request here: https://github.com/emqx/emqx/issues/2676. @gilbertwong96  What where you thinking to do for emqx_auth_cookie? Would it check if the session_id is present in a certain table (SQL request) or make an HTTP call?

In this page(https://docs.emqx.io/broker/latest/en/introduction/checklist.html) I can see 'Browser cookie authentication'.

I'm sorry but I'm a bit confused if this is possible to achieve or not and  how.

I'm happy to contribute but I might need some guidance to decide where and how to implement it.

_Originally posted by @dufourc in https://github.com/emqx/emqx/issues/231#issuecomment-694316546_

**Comment by HJianBo** [comment]
Hi @dufourc Thanks point these problems here.  Your understanding is absolutely correct,  the 'emqx_auth_cookie' or 
'Browser cookie authentication' is not supported now.

In the previous version, we have get the WebSocket cookies and put it into ClientInfo, But it doesn't use these values in any of the authentication plugins.

In addition to supporting the use of placeholders to read common attribute values in ClientInfo, e.g. %c - Client ID, %u - Username. We should also support getting any attribute value in ClientInfo, or ConnInfo, e.g. `$clientinfo.ws_cookie.session_ id`.

**Comment by dufourc** [comment]
So is the strategy:

1. To create another plugin that allow to authenticate with cookies (emqx_auth_cookie) OR
2. To enhance previous plugins(http, database ones..) to add session id in the placeholder coming from $clientinfo.ws_initial_headers.Cookie?

I don't know how the first one would work because we would need to specify a connector to check the information which was the purpose of the existing plugins. (sql, http)

The second one would work fine for the HTTP request. But it won't be  straightforward for the SQL plugins. For example, the MySQL one is comparing the given password with the result of the query.

How were you thinking to do it?

**Comment by HJianBo** [comment]
Yeh, the second is better and more compatible with original logic : )

Regardless of that plugin, they just need to read the fields inside ClientInfo or ConnInfo to query an authorized User/Password, or ACL rules. e.g:
 - In `emqx-auth-http`: the query params can be:
    ```
    auth.http.auth_req.params = session_id=${ clientinfo.wscookie.session_id }
    ```
- In `emqx-auth-mysql`: the auth query SQL can be:
   ```
   select password from mqtt_user where session_id = ${clientinfo.wscookie.session_id} limit 1
   ```

It first requires us to map out a reasonable ClientInfo and ConnInfo structure ( to be honest, these structures are not clear in 4.x ), So it's better to enhance it in 5.0 (Because we have no plan to release new minor for emqx)

**Comment by HJianBo** [comment]
You can improve the code here https://github.com/emqx/emqx-auth-http/blob/master/src/emqx_auth_http_cli.erl#L78  if you need it now.

The detailed ClientInfo defined here:  https://github.com/emqx/emqx/blob/fa31062a5ed673ddbd0ffcdd4b829c3dba2a911d/src/emqx_types.erl#L129

**Comment by dufourc** [comment]
Thanks for your help!

> Yeh, the second is better and more compatible with original logic : )
> 
> Regardless of that plugin, they just need to read the fields inside ClientInfo or ConnInfo to query an authorized User/Password, or ACL rules. e.g:
> 
>     * In `emqx-auth-http`: the query params can be:
>       ```
>       auth.http.auth_req.params = session_id=${ clientinfo.wscookie.session_id }
>       ```
> 

I agree with that one, exactly what I want to be able to do.

>     * In `emqx-auth-mysql`: the auth query SQL can be:
>       ```
>       select password from mqtt_user where session_id = ${clientinfo.wscookie.session_id} limit 1
>       ```
> 

Here it's a bit more complex, because my client doesn't pass any password but only username/session_id. My client(browser) logs in calling an API which saves the session. Then the client is starting a connection with EMQX.
That's why I think the logic will be a bit different. I don't really know how we could define a success for this call. Select sessionId and compare it with the cookie? But the session_id will be used in the where clause. so it's a bit silly.
 
> 
> It first requires us to map out a reasonable ClientInfo and ConnInfo structure ( to be honest, these structures are not clear in 4.x ), So it's better to enhance it in 5.0 (Because we have no plan to release new minor for emqx)

Is this something you want to solve in this issue?

> You can improve the code here https://github.com/emqx/emqx-auth-http/blob/master/src/emqx_auth_http_cli.erl#L78 if you need it now.

Thanks, I will do that and try it out locally, it will be a first good step.

**Comment by dufourc** [comment]
Hey @HJianBo, I've tried the emqx-auth-http plugin and this is working well in docker without the cookie. Then I tried to customised it to add the cookies but I'm a bit stuck on different topics. I'm completely new to Erlang, I read the documentation and I might have silly questions. 

1. On the development flow. How do you try locally your changes for a single plugin? I've follow the steps here: https://github.com/emqx/emqx-rel. 
   - Install Erlang/OTP-R21.3 and rebar3
   - Clone https://github.com/emqx/emqx-rel
   - Fork https://github.com/emqx/emqx-auth-http => https://github.com/dufourc/emqx-auth-http
   - Change the rebar.config of emqx-rel to use my fork instead: {emqx_auth_http, {git, "https://github.com/dufourc/emqx-auth-http", {tag, "v4.2.1"}}}
    - TARGET=emqx/emqx make docker and use this new image in my docker-compose.yml

Then for every changes, I need to:
- Push my changes to emqx-auth-http (my fork)
- Rebuild the image (mainly compile emqx)

Is there any way (with or without docker to compile once emqx and then only compile the plugin emqx-auth-http when I have a change? How are you doing? Because the whole compilation is about 10minutes.

2. When I read  the types in https://github.com/emqx/emqx/blob/fa31062a5ed673ddbd0ffcdd4b829c3dba2a911d/src/emqx_types.erl#L129, client_info has a ws_cookie attribute but if I looked into the code ws_cookie is used once in the ConnInfo in https://github.com/emqx/emqx/blob/master/src/emqx_ws_connection.erl#L222. ConnInfo doesn't have it in the type. And we don't have access to it in emqx-auth-http.

3. I saw that ws_cookie is supposed to be a list. I would have expected a map: {Key => Value}. Is it a list [{K1,V1}, ..., {Kn,Vn}]?

4. You said they won't be any other minors released for EMQX in 4.x. Does that mean that the emqx-auth-http plugin can't be released either? Because I supposed the dependencies(plugins here) have a fixed versions saved in a lock file.

So far, I've tried to add here https://github.com/emqx/emqx-auth-http/blob/master/src/emqx_auth_http_cli.erl#L78 : 

({Param, "%s"}) -> {Param, maps:get(ws_cookie, ClientInfo, null)};

which makes EMQX crash completely.

I suppose I need to add some condition to handle the case when the ws_cookie is not present for none ws connection. And as well, knowing how to access to the key session_id.

I was thinking to add a configuration for the name of the key.

**Comment by HJianBo** [comment]
Q1. After modified the emqx-auth-http dependency repository address and compiled it, your just need:
     1.  Use `make` command to compile it first to ensure the emqx-rel clone all dependencies repository.
     2. Modify your codes at `_checkout/emqx_auth_http/` directory.
     3. Recompile it under the `emqx-rel` root path. It will generate the emqx executable program in the  `_build/emqx/rel/emqx` directory. You can run it by `bin/emqx start` or `bin/emqx console`

Q2. **It should be added to clientinfo, we plan to fix this in 4.2.2 **

Q3. Yes, it is a proplist, e.g: `[{<<"session_id">>, <<"123456">>}, {<<"Kn">>, <<"Vn">>}]`

Q4. Yes, `emqx-auth-http` is not planning a 4.3.x release either. They will only make bug-fixing releases, such as 4.2.2, not functional changes, such as 4.3.0.

**Comment by dufourc** [comment]
Thanks @HJianBo for all your answers, this is really helpful.

So if I want to customise the emqx-auth-http plugin with cookie, I need to wait for the emqx 4.2.2?  Do you have any time estimation about when 4.2.2 is supposed to be released?

Once this is done, I'm happy to try to make a PR for  emqx-auth-http plugin v5.

**Comment by HJianBo** [comment]
haha, It could be released after Friday of next week :)

**Comment by dufourc** [comment]
Amazing, thanks!

**Comment by luisheres** [comment]
Hi! In the introduction for [EMQX 4.4.0](https://www.emqx.io/docs/en/v4.4/#features-list) it is clearly stated that Browser Cookie Authentication is supported. I cannot find any documentation on how to use this feature and unfortunately I can't figure out how the feature is supposed to work from the code. Is there anywhere a description on how to use this feature?

**Comment by HJianBo** [comment]
Sorry, @luisheres. We didn't eventually include this feature in the standard version (mostly because I forgot to track it...)

Ping @savonarola and @id for reviewing this feature
