### ISSUE TITLE
Does EMQx supports multiple Root CA certificate

### ISSUE THREAD

**Issue by outminder** [emqx/emqx#3843]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
Does EMQx supports multiple Root CA certificate. I couldn't find a way to do this via the config file. There are use cases where the Broker/s supports different clients signed by different Root CAs

**Comment by zmstone** [comment]
Hi @outminder 

The easy way out would be to trust the client's CAs in operating system.

Otherwise you may try to collect the trusted CAs in the `cacertfile` config.
According to OTP document : https://erlang.org/doc/man/ssl.html#type-server_cafile

>Path to a file containing PEM-encoded CA certificates. The CA certificates are used to build the server certificate chain and for client authentication. The CAs are also used in the list of acceptable client CAs passed to the client when a certificate is requested. Can be omitted if there is no need to verify the client and if there are no intermediate CAs for the server certificate.

Presumably, the plural word `certificates` is limited in referring to certificates in a single chain,
but can be multiple unrelated roots.

**Comment by outminder** [comment]
Thanks @zmstone this is helpful
