### ISSUE TITLE
ACL API Endpoint not found in 4.3-rc.1

### ISSUE THREAD

**Issue by umeat** [emqx/emqx#4428]
**Environment**:

Docker image emqx/emqx:4.3-rc.1.

**What happened and what you expected to happen**:

The ACL API endpoint used to be /api/v4/emqx_acl, then it was /api/v4/mqtt_acl, and now neither seem to work. 

**How to reproduce it (as minimally and precisely as possible)**:

Run the docker image with emqx_auth_mnesia plugin enabled and exec into the container and run:

```
bash-5.0$ curl localhost:8081/api/v4/mqtt_acl -u admin:public
Not found.

bash-5.0$ curl localhost:8081/api/v4/emqx_acl -u admin:public
Not found.
```

**Anything else we need to know?**:

**Comment by tigercl** [comment]
@umeat Now this part of the feature is provided by the `emqx_auth_mnesia` plugin, so maybe you need to load this plugin first.

**Comment by umeat** [comment]
If I run 4.3-rc.1 in docker with the plugin loaded neither endpoints work.

```
 docker run --rm -it -e EMQX_LOADED_PLUGINS=emqx_auth_mnesia --name emqx -p 18083:18083 -p 1883:1883 emqx/emqx:4.3-rc.1 bash
bash-5.0$ emqx start
EMQ X Broker 4.3-rc.1 is started successfully!
bash-5.0$ curl localhost:8081/api/v4/mqtt_acl -u admin:public
Not found.
bash-5.0$ curl localhost:8081/api/v4/emqx_acl -u admin:public
Not found.
```

I confirmed the plugin is loaded correctly in the dashboard.

**Comment by k32** [comment]
Looking at the code (emqx_acl_mnesia_api.erl), the REST API schema changed once again:

On 4.3:
```
-rest_api(#{name   => list_clientid,
            method => 'GET',
            path   => "/acl/clientid",
            func   => list_clientid,
            descr  => "List available mnesia in the cluster"
           }).
...
```

On 4.1 (which you were using before):

```
-rest_api(#{name   => list_emqx_acl,
            method => 'GET',
            path   => "/emqx_acl",
            func   => list,
            descr  => "List available mnesia in the cluster"
           }).
...
```

**Comment by umeat** [comment]
Okay thanks. Confirmed that works.

The 4.3 doco still says "emqx_acl": https://docs.emqx.io/en/broker/v4.3/advanced/acl-mnesia.html#use-the-http-api-to-manage-acl-rules

**Comment by zmstone** [comment]
this is not nice. 
we should make it backward compatible. 
@k32 thank you for your support, could you send a PR to make it compatible ?

**Comment by zmstone** [comment]
this is due to enterprise code disclosed to the community.
should have done a better job reviewing the change...

**Comment by k32** [comment]
@zmstone Sure. Seems like it was a side-effect of merging code enterprise and opensource codebases in the monorepo. (Commit:  e236196fa61152f9850aeffc49b2b350d9a9ed47 that switched `emqx_auth_mnesia` to e4.2 tag) I am trying to understand what is the best course of action, because the branches diverged quite a bit.

**Comment by zmstone** [comment]
we can add back the old endpoint and delegate the call the the new.

**Comment by k32** [comment]
Turns out the changes in the API can't be trivially mapped to one another. We'll come back to you when we decide the way forward.

**Comment by zmstone** [comment]
I'm afraid 4.2->4.3 upgrade, configuration and API compatibility is broken.

The same thing happened for enterprise 4.1->4.2
^ this is no excuse for non backward-compatible change for open-source though
however we can not let the code diverging even more, otherwise nobody benefits from it.
Hope our open source users will understand it. We'll make sure this is stated in the release notes.

I am closing this issue for now.
Will follow up the API document changes here:
https://github.com/emqx/emqx-docs/issues/716

**Comment by zmstone** [comment]
edited: the broken compatibilities are only about emqx_auth_mnesia plugin.

**Comment by umeat** [comment]
No stress. Love your work.
