### ISSUE TITLE
Netsplit and load balancing

### ISSUE THREAD

**Issue by elisiariocouto** [emqx/emqx#478]
Hi @erylee,

First of all, amazing job! I want to ask you a few questions:
1. I have an emqttd node (0.16) running for a few days with approximately 1500 clients: ~1450 publishers with one message per second and ~50 subscribers. Although, we are having a few errors on the subscribers. We are using Paho's Go client lib and, sometimes, we are having the following error `disconnected from broker: pingresp not received, disconnecting`. Also, I can see some dropped messages on the emqttd dashboard. On the front of the broker we have an HAProxy but I find it very odd if this behaviour is HAProxy-related. Do you have any idea about this problem?
2. I want to move to a clustered design. I saw on the documentation that the brokers do not recover automatically from a netsplit. Is this true or you have already implemented that in the current version (0.17)?
3. For this clustered design I want to do some load balancing. What do you think is the best approach to do that on emqttd? HAProxy? nginx? Random broker IPs on the client? DNS round robin?

Thanks for the help, keep up with the good work!
Cheers

**Comment by hsncr** [comment]
@elisiariocouto maybe some of your configs are not correct. you need to set _timeout client_ config to a value that is greater than your client keep alive value as they stated below link.

https://github.com/mqttjs/MQTT.js/issues/37

**Comment by hsncr** [comment]
There is this issue but I don't know if it is related with emqtt or haproxy. I don't know how to test it.

I am using haproxy for load balancing. For following scenario, I lost all undelivered messages. 

- 2 clients connect and subscribe to a topic, start to publish. 
- One of them gets disconnected intentionally or  because of net connectivity problem.  
- Other one continue to publish messages.
- When disconnected client attempts its first connect, I get following behaviour;

1. Client attempt to connect.
2. Received connected callback.
3. Received disconnected callback.
4. And then disconnected by broker event received.
5. All undelivered messages are gone now.
6. After reconnect Client receives last message that has been sent.

If I connect client directly to broker, it works as it should be.

Any ideas?

**Comment by w3yyb** [comment]
has fixed?

**Comment by zhengyupan** [comment]
@elisiariocouto It is fixed in version 2.3.
Please refer to this document for information about automatically recovery from netsplit:
https://emq-docs-en.readthedocs.io/en/latest/cluster.html#network-partition-and-autoheal
