### ISSUE TITLE
init_resource failed

### ISSUE THREAD

**Issue by moziie** [emqx/emqx#5017]
this is the logs:
2021-06-17T01:22:54.026221+00:00 [warning] [Rule Monitor] init_resource failed: 
{throw,{{emqx_web_hook_actions,on_resource_create},{error,undef,[{persistent_term,get,[{emqx_misc,ipv6_probe_supported},unknown],[]},
{emqx_misc,ipv6_probe,1,[{file,"emqx_misc.erl"},{line,65}]},{emqx_web_hook_actions,pool_opts,2,[{file,"emqx_web_hook_actions.erl"},
{line,339}]},{emqx_web_hook_actions,on_resource_create,2,[{file,"emqx_web_hook_actions.erl"},{line,193}]},{emqx_rule_engine,'-init_resource/4-fun-0-',4,
[{file,[...]},{line,...}]},{emqx_rule_engine,init_resource,4,[{file,...},{...}]},{emqx_rule_monitor,retry_loop,3,[{...}|...]}]}}}, 
[{emqx_rule_engine,'-init_resource/4-fun-0-',4,[{file,"emqx_rule_engine.erl"},{line,520}]},{emqx_rule_engine,init_resource,4,
[{file,"emqx_rule_engine.erl"},{line,520}]},{emqx_rule_monitor,retry_loop,3,[{file,"emqx_rule_monitor.erl"},{line,107}]}]
##emqx version;
Node 'emqx@127.0.0.1' 4.3.3 is started
##Installation method
Source code compilation and installation
please help me.thanks

**Comment by moziie** [comment]
![image](https://user-images.githubusercontent.com/70946068/122322902-cdb20600-cf58-11eb-9490-0f21e053649d.png)

**Comment by k32** [comment]
Hello,
Which version of Erlang/OTP are you using?
The error tells that `persistent_term:get/2` function is undefined, but this function is a part of Erlang standard library since OTP 21.3, so it should always be present if you use the supported version of Erlang. 
Can you do a clean installation from the source code using, preferably on OTP23? Feel free to reopen the issue if you still see the issue.
