### ISSUE TITLE
The rule engine is not working as expected

### ISSUE THREAD

**Issue by wenlian** [emqx/emqx#5354]
The rule engine is not working as expected and got a confusing result
VERSION：`4.2.11 and 4.3.5`
MESSAGE：`{"id":"9999","devices":[{"deviceId":"test","deviceState":1,"deviceData":{"kt1":32.75,"kh1":61.89,"c1":436,"g1":20,"st1":29.11}}]}`
RULE SQL：
1. `SELECT payload as msg 
FROM "gy/gh98/data" 
WHERE msg.devices[0].deviceData.st1<30
`
2. `FOREACH
  payload.devices
DO
  payload as msg,
  item.deviceData.st1 as st1
INCASE
  st1 < 30
FROM "gy/gh98/data"
`

The rule  1 will not be triggered whether 'st1' is less than '30' or lager than '30', but the rule 2 will be triggered in both cases.
if we replace the '<' with '>'，The rule 2 will not be triggered whether 'st1' is less than '30' or lager than '30'... The situation is just the opposite..

**Comment by terry-xiaoyu** [comment]
The doc might not be clear enough for `FOREACH-DO-INCASE` clauses, but in `INCASE` you cannot use the exported variables by `DO` clause. So for your 2nd example, you should change it to this:

`FOREACH payload.devices DO payload as msg INCASE item.deviceData.st1 < 30 FROM "gy/gh98/data"`

For your first example, that is your array index which caused `msg.devices[0].deviceData.st1` return nothing, because we use array index start from `1` not `0`：

`SELECT payload as msg FROM "gy/gh98/data" WHERE msg.devices[1].deviceData.st1<30`

Hope this helps.

**Comment by wenlian** [comment]
> The doc might not be clear enough for `FOREACH-DO-INCASE` clauses, but in `INCASE` you cannot use the exported variables by `DO` clause. So for your 2nd example, you should change it to this:
> 
> `FOREACH payload.devices DO payload as msg INCASE item.deviceData.st1 < 30 FROM "gy/gh98/data"`
> 
> For your first example, that is your array index which caused `msg.devices[0].deviceData.st1` return nothing, because we use array index start from `1` not `0`：
> 
> `SELECT payload as msg FROM "gy/gh98/data" WHERE msg.devices[1].deviceData.st1<30`
> 
> Hope this helps.

it works for me. thx  ∩_∩ !
