### ISSUE TITLE
Why do I frequently disconnect and reconnect when the device ID is not the same?

### ISSUE THREAD

**Issue by qzgyw** [emqx/emqx#5500]
There is one device under the two routers, and the IP of the two devices is the same. Because the IP of the router is different, it will not be repeated. However, after connecting to EMQX, it will be frequently disconnected and reconnected, is it not allowed to have the same IP?

**Comment by qzhuyan** [comment]
Do you mean your MQTT device is behind NAT and the two routers have the same external IP?

**Comment by qzgyw** [comment]
Thank you for your answer. It is not the same external IP address, but two external IP addresses connected to two routers. However, after the NAT mode of the routers, the IP addresses of the two devices are the same.@qzhuyan

**Comment by qzhuyan** [comment]
I see, so the devices is flipping the transport since it is behind the two routers, I think you should look into the source port on transport instead. if the IP & port is the same or not.

To emqx, if the source IP&Port are different, they are different connections.

I close the ticket now, if you need more help either create new ticket or reopen this one.
