### ISSUE TITLE
Heap Size Loop - maximum heap size reached

### ISSUE THREAD

**Issue by bbustan** [emqx/emqx#5717]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
Node 'e2eemqx@e2eemqx-0.e2eemqx-headless.e2e.svc.cluster.local' 4.3.8 is started
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:
Running on Kubernetes

**What happened and what you expected to happen**:
We're sending a file from device ID 1PC4200AB3005432159950 , the filesize is 1.2MB .
It is received by the broker but failed with the error  "maximum heap size reached" , I've update the configuration to  EMQX_ZONE__EXTERNAL__FORCE_SHUTDOWN_POLICY to 64000|180MB
still the Heapsize reach 29MB for some reason while the file is only 1.2MB.
Attached the emqx logs , could you please advise why the heapsize is getting bigger then the filesize ? 

[e2eemqx-0.log](https://github.com/emqx/emqx/files/7149594/e2eemqx-0.log)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by qzhuyan** [comment]
@bbustan

 Looks like it is caused by 
1. high rate of 1.2M messages 
1. debug logging for high rate of 1.2MB messages. Logging copies the binary to heap cause the heap size bump. if you turn off the logging, you don't need such big heap to handle it, I think. 

Could you retry with debuglog off? 

also you can turn off the policy by set it to `0` to see how much it actually needs.

**Comment by bbustan** [comment]
@qzhuyan 
1. Where did you saw the high rate of 1.2M messages ? 
2. We're talking about 1.2MB data , i setup the heap to 128MB it should make it full ? what am i missing ? 
3. I setup the turn off policy to 0 and the process crashed due to out of memory (i set 1GB ram for the pod) - attached log from the crash 
4. When i change the debug level to error it works

Thanks for your prompt response 

[e2eemqx-2.log](https://github.com/emqx/emqx/files/7153787/e2eemqx-2.log)

**Comment by qzhuyan** [comment]
> 1. Where did you saw the high rate of 1.2M messages ?

I mean high rate of 1.2MB messages

I see 406 msg/s in last log file
```
 grep -c "12:49:26.*1PC4200AB3005432159950@10.36.0.0:26876.*RECV" e2eemqx-0.log
 406
```

> 2. We're talking about 1.2MB data , i setup the heap to 128MB it should make it full ? what am i missing ?
> 3. I setup the turn off policy to 0 and the process crashed due to out of memory (i set 1GB ram for the pod) - attached log from the crash
Depends on when the process start to do garbage collection, my assumption is debug logs put tones of garbage in the process heap and process heap keep growing until it hits the max heap limit then it get killed.

If you still want to keep the debug log ON, you could make GC more frequent by setting the envvar `ERL_FULLSWEEP_AFTER` to 10 (default is 65535) that will bump the CPU load in exchange.

> 4. When i change the debug level to error it works

Good. If debug is OFF, the 1.2MB message will be kept in shared binary heap that keeps the connection process heap low because in connection process it is just a reference to the shared binary heap instead of entire message.

I closed the ticket for now since the root cause is clear now, feel free to reopen it when needed.
