### ISSUE TITLE
Error in Make (EMQ X 4.3; Ubuntu 20.04.3; Erlang/OTP 22)

### ISSUE THREAD

**Issue by quangnnnexuss** [emqx/emqx#5839]
### Subject of the issue
Describe your issue here.
Build from the source. Got error in run "make"
===> Compiling apps/emqx_rule_engine/src/emqx_rule_runtime.erl failed
emqx_rule_runtime.erl:259: function binary_to_existing_atom/1 undefined

make: *** [Makefile:78: emqx] Error 1

### Your environment
OS: Ubuntu 20.04.3

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): Linux quang 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Erlang/OTP version (in case you build emqx from source code):  Erlang/OTP 22
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 
clone the source  and Make

### Expected behaviour
Tell us what should happen
Make completed!

### Actual behaviour
Tell us what happens instead
Error in run "Make"

Missing log file can delay the handling of the issue.

**Comment by zmstone** [comment]
This can be worked around with OTP 23 (which is also the recommended version for EMQ X 4.3)
We'll fix it in the next bug fix release.

**Comment by Spycsh** [comment]
You said that you build with EMQ X version 4.3 but it seems not to be that case as shown from the error message. Do you just clone the master(default) branch and do make with OTP 22? That will cause the problem as shown in the error message. Here are two choices you can adopt:

If you want to use EMQ X 4.3 with OTP 22, you must fetch branch **main-v4.3**. Otherwise, if you want to use the master branch, which currently is EMQ X 5.0, you must build with OTP 23 or 24.

**Comment by zmstone** [comment]
Thank you @Spycsh 
I'm closing this issue now @quangnnnexuss,
you are welcome to open a new issue if there is anything wrong building `master` branch on OTP 23/4, and `main-v4.3` branch on OTP 22/23.
