### ISSUE TITLE
auth_pgsql ACL does not work

### ISSUE THREAD

**Issue by eleleme** [emqx/emqx#5884]
### Subject of the issue
auth_pgsql启动的情况下，添加主题控制 /smarthome/%c/temperature的pub/sub权限，mqtt client能pub和sub主题/smarthome/{不是clientid}/temperature的主题，看上ACL没起作用。请问如何限制client只能订阅和发布 /smarthome/%c/temperature，其他主题deny？

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Missing log file can delay the handling of the issue.
![acl_1](https://user-images.githubusercontent.com/3699702/136363834-8230a6f2-6732-4ea8-ae1f-31dd9a214b17.png)
![acl_2](https://user-images.githubusercontent.com/3699702/136363853-fba55246-705a-4bf9-94f5-30cd0a39d28d.png)

**Comment by Spycsh** [comment]
Hi @eleleme ,

I tried to reproduce your problem and found there should be something wrong with your steps. I notice that you have successfully connect to postgres plugin for ACL. Your assumption is also correct, if you set pub/sub access to topics which match `/smarthome/%c/temperature` and since %c represents the current client id, one client should only pub/sub to the topics with its own client id. 

However, I notice that in your postgresql table columns (although it seems somewhat indistinct), you just have one line that assign `ipaddr` and `clientid` to be null, and `username` to be $all. You have to add an extra line to tell ACL that you need to filter out all the other cases that one client cannot pub/sub messages to topics of other clients as follows:

|allow|ipaddr|username|clientid|access|topic|
|:---:|:---:|:----:|:----:|:---:|:---:|
|0|null|$all|null|1|/smarthome/+/temperature|
|1|null|$all|null|1|/smarthome/%c/temperature|

**Comment by zmstone** [comment]
@Spycsh thank you for the investigation.
We'll keep this issue open until doc is improved.
Please link the doc fix PR to this issue.
