### ISSUE TITLE
PostgreSQL authentication scenarios when terminating TLS at load balancer

### ISSUE THREAD

**Issue by ilarimikkonen** [emqx/emqx#6553]
### Load balancer TLS termination, PostgreSQL authentication and %C

The PostgreSQL authentication [documention](https://docs.emqx.io/en/broker/v4.3/advanced/auth-postgresql.html#salting-rules-and-hash-methods) discusses the possibility of using "TLS certificate common name", %C when performing authentication. 

In which scenarios is it possible to use this method? Is it necessary to terminate the encryption at the EMQx broker fo this to work? 

We have a case, where we are terminating TLS at load balancer, is there any way to propagate cert common name to the EMQx broker and then to the plugin? 

### Your environment
N/A
### LOG File
N/A

### Other material:
https://www.emqx.com/en/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

**Comment by thalesmg** [comment]
Hi @ilarimikkonen !

The TLS Certificate Common Name mentioned in the docs refer to the SSL connection between the EMQX Broker and the PostgreSQL server, which is not related to the SSL termination that MQTT clients may use to connect to the EMQX Broker.  The blog post you linked is related to the later, while the documentation linked is related to the former.

So, in order to use the `%C` parameter in your authentication query, you have to configure the [SSL options](https://docs.emqx.io/en/broker/v4.3/advanced/auth-postgresql.html#postgresql-connection-information) for the _PostgresSQL_ connection (the `auth.pgsql.ssl*` ones), and then you should be able to refer to `%C` in the [authentication query](https://docs.emqx.io/en/broker/v4.3/advanced/auth-postgresql.html#auth-query).

**Comment by ilarimikkonen** [comment]
Ok, thanks for fast the reply, you guys are the best! My mistake. Is there any way of using Common Name, Origin Header, or any header coming from mqtt client when doing Authentication using PostgreSQL plugin? I understood that the EMQx has an Origin Header white list, but it's a flat list, that's all.

**Comment by zmstone** [comment]
Proxy protocol v2 forwards SSL information as the so-called sub-type data to the backend.
ref: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

```
2.2.6. The PP2_TYPE_SSL type and subtypes

For the type PP2_TYPE_SSL, the value is itself a defined like this :

        struct pp2_tlv_ssl {
                uint8_t  client;
                uint32_t verify;
                struct pp2_tlv sub_tlv[0];
        };

The <verify> field will be zero if the client presented a certificate
and it was successfully verified, and non-zero otherwise.

The <client> field is made of a bit field from the following values,
indicating which element is present :

	#define PP2_CLIENT_SSL           0x01
	#define PP2_CLIENT_CERT_CONN     0x02
	#define PP2_CLIENT_CERT_SESS     0x04
```

in EMQ X, you can make use of them as client ID with the tcp listener config: `listener.tcp.external.peer_cert_as_username = cn`
ref: https://docs.emqx.io/en/broker/v4.3/configuration/configuration.html#listener-tcp-external-peer-cert-as-username

Once common name is used as MQTT username, it can be used in auth backends such as postgres with the `%u` placeholder.
ref: https://docs.emqx.io/en/broker/v4.3/advanced/auth-postgresql.html#auth-query
