### ISSUE TITLE
Username Enumeration

### ISSUE THREAD

**Issue by GYWF** [emqx/emqx#6791]
### Subject of the issue
When a user login, the application returns different results depending on whether the account is correct  that allowed an attacker to determine if a given username was valid.

### Your environment

EMQ X 3.x

### Steps to reproduce
The problem lies in the "/api /v3/auth" interface

If you log in using an existing account and the Password is incorrect, "Password Error" is displayed.
![image](https://user-images.githubusercontent.com/35076979/150079509-0059e80a-26dd-48a2-b4ae-814eb82a107c.png)

and "Username Not Found" is displayed when you log in using a non-existent account.
![image](https://user-images.githubusercontent.com/35076979/150079882-dc2db524-3d15-4213-a7f4-4ae664ab81ab.png)

**Comment by thalesmg** [comment]
Hi @GYWF !

Thank you for your report!

That version of EMQ X (3.x) is no longer supported.  Fortunately, on the latest 4.3.11 (`/api/v4/auth`), that issue is now resolved.  Not only you have to be already authenticated to use this API, but the return is the same for both non-existent users and wrong passwords:

```sh
$ curl -su 'admin:public' -XPOST http://localhost:8081/api/v4/auth -d '{"username": "admin", "password": "wrongpass"}' | jq .
{
  "message": "Username/Password error"
}

$ curl -su 'admin:public' -XPOST http://localhost:8081/api/v4/auth -d '{"username": "wronguser", "password": "somepass"}' | jq . 
{
  "message": "Username/Password error"
}
```

Please, feel free to open another issue if you find similar problems in the current versions!
