### ISSUE TITLE
Still Getting "Authenticity Validation" Warning Despite Updating All Config Files And Using "Purchased" SSL Certs

### ISSUE THREAD

**Issue by domiluci** [emqx/emqx#7875]
### Subject
I was able to obtain an SSL certificate for my server through ZeroSSL, so I am *not* using a self-signed certificate. The certificate works as I'm able to connect to the server and its node and sub/publish through it over SSL quite beautifully. The files I've updated to use the ZeroSSL certificate and CA's `ca_bundle.crt` file is `emqx.conf` (for all listeners) and `ssl_dist.conf`.

But I receive the following warning in the EMQX console every time after I start EMQX by running "./emqx console" in PowerShell:
`[warning] Description: "Authenticity is not established by certificate path validation", Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"`.

I've tried everything (what little there was) that I found online. Still getting the warning. And I know it's not a fatal issue, but I'd feel better if I could just fix it as the less bugs the better. So thank you guys in advance; Erlang isn't my first language.

### Environment

I can't get `node_dump` to run on my system, but I'll do my best to outline my setup

Otherwise please provide below info:
- EMQ X v4.4.3 (pre-built for Windows)
- Just a single node right now until I smooth out the bugs
- I'm running a t2.micro instance on AWS at the moment as my personal server is struggling with our current ISP and I'm up against a deadline and strapped for cash
- Windows Server 2022 Datacenter
- Erlang/OTP version: v24.2.1

### ssl_dist.conf

[ssl_dist.conf.txt](https://github.com/emqx/emqx/files/8634565/ssl_dist.conf.txt)

### emqx.log.1

[emqx.log.1.txt](https://github.com/emqx/emqx/files/8634572/emqx.log.1.txt)

**Comment by domiluci** [comment]
I've updated *both* the `emqx.conf` and `ssl_dist.conf` files with all the pertinent information regarding my SSL certificates, including those settings you have listed. Yet I'm *still* getting the warning in the EMQX console when I start up EMQX each time.

I had an issue the last couple days that prevented me from responding or working on this at all (my broadband modem decided 6 days to deadline was the perfect time to *literally* die, but thank God for Amazon Prime). So I'm just now able to work on this further. I will quintuple check all these settings yet again, but I'm positive I've updated everything you're saying I need to and gone over it several times. Yet I am still receiving the error, so... I don't know. I'll just check again and update in a little while with my progress.

Thank you.

**Comment by domiluci** [comment]
So @zmstone , I'm a bit confused here. I could not find any of the settings you mentioned in your post in `emqx.conf`, and adding them causes a bunch of errors to be thrown and the console to crash. So where are those settings supposed to be located and used?

**Comment by zmstone** [comment]
Hi @domiluci 
This alarm is harmless.
It's simply warns us that, as I wrote:
> it tells us that some SSL options are ambiguous in safety-ness, one should either

Please do not let it be a blocker.

More info:

Now that I checked again, I have a pretty good idea where the issue is, and will submit a PR soon.
Long story short: in the linux releases, we had the warning suppressed, but not Windows.

**Comment by domiluci** [comment]
I know it's harmless. I'm just a perfectionist.... 😅

But you're saying it's a bug on Windows? Interesting.

Okay, well, I guess I'll just leave it be as is then. It doesn't sound like there's a viable resolution and I don't have time to keep tinkering with it. Thank you for your help. I really appreciate it.

**Comment by zmstone** [comment]
Not really a bug, just an warning to get people's attention for better safety.

This warning was introduced in Erlang/OTP 24,
in the beginning, it's on even if it was very specifically told not to care,
so we had to fork Erlang/OTP with a patch to make it behave like version 23.
Later (forgot which exact version, but at least since version 24.2.1), it's fixed to warn when the safety option is not clear,
but our patch remained.

Our patch was only added to Linux distributions, but not Windows.
Now since the Windows distribution is on 24.2.1, we can fix the warning with a specific `verify_none` option.

**Comment by domiluci** [comment]
Interesting. I see what you're saying. Thanks for the help and explanation!
