### ISSUE TITLE
cluster deploy

### ISSUE THREAD

**Issue by forest-yang** [emqx/emqx#835]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: 2.0

#### Description
When deploy under cluster environment, I have seen a description, EMQ will keep copy of Topic <-> Node mapping among all nodes, if 1M or even 2M clients connects to broker, there wil be lots of resources (memory) will be consumed of each node, right? can mapping keep out of broker, e.g., redis or other in-memory database and used by all broker?

*A description of the issue*

**Comment by turtleDeng** [comment]
@forest-yang http://emqtt.com/products#price

**Comment by forest-yang** [comment]
I have seen this description: "Every node in the cluster will store a topic trie and route table in mnesia database.". is it possible to store topic & client out side broker?

**Comment by emqplus** [comment]
@forest-yang The topic trie and routing table will be replicated to each node in the cluster. And we are working on a micro service architecture these days to separate the connection and routing layer.

**Comment by forest-yang** [comment]
@emqplus ,thank you, are there any plan of this feature ( exposure a micro service to separate the connection and routing layer ) ?

**Comment by zmstone** [comment]
we have significantly reduced memory footprint for trie storage since 4.3.
with default config, the trie table costs 144MB to store 1 million 5-level wildcard topics of pattern `device/X/+/Y/#`

WRT scalability, as step-1, we will apply https://github.com/emqx/eip/blob/main/active/0004-async-mnesia-change-log-replication.md

Closing this PR. More discussion are welcome to be posed in the discussion panel (either in this repo or https://github.com/emqx/eip/discussions)
