### ISSUE TITLE
If docker's persistence directories are empty, they should be created

### ISSUE THREAD

**Issue by xray-bit** [emqx/emqx#8424]
### What would you like to be added or enhanced?

>If you want to persist the EMQX docker container, you need to keep the following directories:
>
>/opt/emqx/data
>/opt/emqx/etc
>/opt/emqx/log
>...
>In if you use docker-compose, the configuration would look something like this:
>```
>volumes:
>  vol-emqx-data:
>    name: foo-emqx-data
>  vol-emqx-etc:
>    name: foo-emqx-etc
>  vol-emqx-log:
>    name: foo-emqx-log
>
>services:
>  emqx:
>    image: emqx/emqx:v4.0.0
>    restart: always
>    environment:
>      EMQX_NAME: foo_emqx
>      EMQX_HOST: 127.0.0.1
>    volumes:
>      - vol-emqx-data:/opt/emqx/data
>      - vol-emqx-etc:/opt/emqx/etc
>      - vol-emqx-log:/opt/emqx/log
>```

If `foo-emqx-data` / `foo-emqx-etc` is an empty directory, the docker container will fail to start.

### Why is this needed?

If users need to persist these directories. Then users must first create containers without persistent directories, and then copy these directories from the container. Then create a container with a persistent directory.

I think it should be like other projects, such as mysql. If the relevant files do not exist, they should be created first.

**Comment by zmstone** [comment]
Hi @xray-bit 

`data` dir can be empty before emqx boots.
in `etc` dir though, the configs and so on have to be there before emqx can boot.

`etc` is no longer a volume since `v4.3.13`.
`etc` is very much static, EMQX does not mutate any files in this dir,
so if you have some changes you want to persist, you can simply commit your changes inside the container.
