### ISSUE TITLE
MQTT bridge does not transmit MQTTv5 properties

### ISSUE THREAD

**Issue by danfreund808** [emqx/emqx#9179]
#### Environment

- OS: Ubuntu 22.04 / Docker
- Erlang/OTP: as included in official docker images
- EMQ: 5.0.3, 5.0.8

#### Description

Setup:
- Two brokers running EMQX 5.0.3 on docker
- Broker1 with MQTT bridge set up that forwards incoming MQTT messages to Broker2 using a "MQTT Sink Data Bridge"
- Bridge settings: 
    - MQTT Version: v5
    - Bridge mode: false
    - Topic: bridge/${topic}
    - QoS: ${qos}
    - Payload: ${payload}
- Rule settings:
    - SQL-Editor: SELECT * FROM "mytopic/#"
    - Action: Forwarding with DataBridge

Expected behavior:
- Sending MQTTv5 messages from Broker1 -> Bridge -> Broker2 sends the message transfers the complete message (payload, qos, **properties**, ..)
- No loss of information when using bridge

Actual behavior:
- Bridging of messages works for payload and qos. However, MQTTv5 properties are empty on the receiving side (**no custom properties, no Content Type property**)
- See attached screenshot with properties (left) and without (right) after receiving message from bridge

Remark: Experienced the same behavior on EMQX 5.0.3 and 5.0.8. 

![screenshots](https://user-images.githubusercontent.com/81414265/196716950-2203780e-a015-45e2-82d2-26c4d59ca890.png)

Thanks for looking into this!

**Comment by nosovk** [comment]
I can confirm the issue on 5 branch of EMQX. Properties are removed when passed by bridge.

**Comment by kraftwerk28** [comment]
User properties might be lost at the Rule level, because I can reproduce it even when there is no Bridge involved (i.e. Rule with just Republish action). Notice, that User properties are present in the payload; I defined the `payload` as `${payload} | ${pub_props}` in the Republish action. However, they aren't present in the packet itself.
![image](https://user-images.githubusercontent.com/31807671/197252562-51e938a7-6ee1-43c7-a541-48d161d8113e.png)

**Comment by danfreund808** [comment]
I can confirm that the issue is fixed in EMQX 5.0.11 for my test setup as in the initial description above.
Thanks for fixing.
