### ISSUE TITLE
Connection reset by peer after Update

### ISSUE THREAD

**Issue by N0tronic** [emqx/emqx#9606]
### What happened?

Since Update from EMQX Version 4.3.17 to 4.3.22 our client connections no longer stable. Message in client logs: "Connection reset by peer"

After a rollback to 4.3.17 the connection is stable again.

### What did you expect to happen?

Stable connections as before the update.

### How can we reproduce it (as minimally and precisely as possible)?

Change Version from 4.3.17 to 4.3.22

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.3.22
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
SUSE Linux Enterprise Server 15 SP4
```

</details>

**Comment by tigercl** [comment]
Hi, @N0tronic 

Are there any error or warning logs in the EMQX log files?

If not, it is best to use [Log trace](https://www.emqx.io/docs/en/v4.4/getting-started/log.html#log-trace-2) to obtain the complete log of the specified client so that we can analyze the cause.

**Comment by zmstone** [comment]
Hi @N0tronic 
It's a good call to upgrade, especially for this change.
> Upgrade Erlang/OTP from 23.2.7.2-emqx-3 to 23.3.4.9-3 [#8511](https://github.com/emqx/emqx/pull/8511)

And thank you for reporting this issue back to us.
We'll try our best to work with you to identify the cause.

I had a quick review of the changes since 4.3.18, below are the changes which might be relevant.

* Is TLS in use? There had been a TLS socket buffering tune-down (to 4K), which is to reduce the amount of RAM consumption. But we have not observed anything odd in our load tests.
* Shared subscriptions?. There were quite a few fixes for shared subscription, when subscribers are non-clean session and tend to often go offline, offline for some time, the amount of messages to re-dispatch may increase and affect the other clients' stability.
* Is flapping detection enabled? (`zone.$name.enable_flapping_detect`). Enhancement in 4.3.21

Need your help to
* It would help if you provide more information about your traffic pattern, and how you have configured EMQX
* If possible (e.g. in a staging environment) try to collect the socket close reasons, e.g. `emqx ctl listeners` can report some statistic number for each client shutdown reason, comparing before/after upgrade might provide us more clues for further investigation.
